### ISSUE TITLE
More ClassicActorSystemProvider

### ISSUE THREAD

**Issue by patriknw** [akka/akka-grpc#1012]
To support typed.ActorSystem.

Some were fixed in https://github.com/akka/akka-grpc/pull/972, but seems to be a few more. Noticed in GrpcClientSettings:

https://github.com/akka/akka-grpc/blob/97601b5063520e0f12235f9de00e93fc0b1be055/runtime/src/main/scala/akka/grpc/GrpcClientSettings.scala#L93

**Comment by raboof** [comment]
(that particular instance was now fixed, but let's check for more before closing this issue)

**Comment by raboof** [comment]
I only found #1017 and the 'custom exception handler', but we're planning on changing the type of the 'custom exception handler' in #928 anyway, so that can wait.
