### ISSUE TITLE
Gradle plugin support for scala 2.13

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-grpc#1024]
The Akka-gRPC plugin for Gradle uses a hardcoded [artifact](https://github.com/akka/akka-grpc/blob/master/gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPlugin.groovy#L143). Because of that users building their project using gradle can only use scala 2.12.

There are two options:

- release different plugins for each scala major akka-grpc supports
- remove the [automatic dependency management](https://github.com/akka/akka-grpc/blob/master/gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPlugin.groovy#L143) from the gradle plugin so users need to add the plugin _and_ add the dependency to `akka-grpc-runtime_2.xx` 

PS. Note the gradle plugin [uses other artifacts](https://github.com/akka/akka-grpc/blob/master/gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPlugin.groovy#L52-L61) hardcoded to 2.12. That's fine because those are only used at source-generation time.

**Comment by eshepelyuk** [comment]
@ignasi35 @raboof - got a comment about #1025 

Althought proposed patch opens the possibility to use Scala 2.13, but it also makes a plugin application more complicated, i..e. forces users to explicitly declare akka grpc runtime dependency.

While plugin should simplify such things, declare dependencies itself, without forcing users to care about exact dependencies and their application via `build.gradle`.

I propose a different approach to unblock Scala 2.13 usage - to introduce a configuration parameter that will be holding versino of Scala, it could be overwritten and it will have default value.

So, `build.gradle` could look like 

```
akkaGrpc {
  scalaVersion = '2.13'
}
```

By default value of `scalaVersion` could be `2.12` - so this change will not introduce compatibility break for existing users of the plugin.

This is quite common approach in Gradle plugins working with Scala libraries. 
I did it for my own plugin and I'm willing to contribute the code with the test if there's no objections from your side.

**Comment by ignasi35** [comment]
This is a great idea. Would you like to work on it? I am fine dropping the exploratory work on the PR.

**Comment by eshepelyuk** [comment]
@ignasi35 sure I do , as mentioned above i will contribute this code.
Maybe during a weekend.

**Comment by eshepelyuk** [comment]
@raboof plz feedback :)
I am also going to introduce tests for my functionality 
And Id like to go with Spock framework, that is a natural choice in groovy language ecosystem.
Tests could be run transparently using `gradlew test`

**Comment by raboof** [comment]
> @raboof plz feedback :)

Sounds great to me! Especially if it's an existing convention in gradle+scala projects - I don't have much gradle+scala experience myself.

**Comment by eshepelyuk** [comment]
@raboof there is no formal convention
Just my experience, as a plugin developer :))

**Comment by ignasi35** [comment]
>  I am also going to introduce tests for my functionality

That'd be great!

**Comment by eshepelyuk** [comment]
Well, in the end the implementation changed, and now scala version will be autodetected.
No need to introduce a configuration parameter
