### ISSUE TITLE
Cannot connect to a gRPC server written in a different language

### ISSUE THREAD

**Issue by mmchougule** [akka/akka-grpc#1044]
I am following this guide to create a simple client that connects to a gRPC server written in python. https://doc.akka.io/docs/akka-grpc/current/client/walkthrough.html
I am getting the following error:
`io.grpc.StatusRuntimeException: UNAVAILABLE: io exception`
Wondering, if I am missing anything here?

**Comment by raboof** [comment]
That should of course definitely work. The first things to double-check would be the hostname and port number, and whether TLS is enabled or not. If that all checks out perhaps running with DEBUG logging enabled might shed some more light on the issue?

If you can boil down your project to something you can easily share and I could run it here I could havve a closer look.

**Comment by mmchougule** [comment]
Okay, thank you! I will check your suggestions and write back.

**Comment by mmchougule** [comment]
Thanks @raboof ! TLS was the issue. It worked after setting `use-tls = false` in application.conf 👍

**Comment by raboof** [comment]
Cool, good to hear! Enjoy!

**Comment by mmchougule** [comment]
Thank you! I have an example, Scala gRPC client for Kedro https://github.com/mmchougule/kedro-grpc-scala-client
