### ISSUE TITLE
Document steps for updating the version of protoc to use (for the Gradle plugin).

### ISSUE THREAD

**Issue by orendain** [akka/akka-grpc#1068]
### Short description

The (Gradle plugin) docs don't outline steps for how to override the version of `protoc` to use.  This is necessary as older versions of `protoc` can not process some protobuf features.  E.g: https://github.com/protocolbuffers/protobuf/issues/3458 and https://github.com/protocolbuffers/protobuf/issues/4322.

### Details

Specifically:
- Document the version of `protoc` and relevant packages that are shipped with the plugin.
- Outline steps for specifying version of `protoc` via someone's `build.gradle` to use in place of embedded lib.
- (optionally) Update the versions of the proto libraries shipped with the Gradle plugin (it's not caught up to the SBT plugin).

I've yet to contribute to the docs - I'm happy to tackle this (perhaps this weekend?) and submit a PR unless someone beats me to it.

**Comment by raboof** [comment]
> I've yet to contribute to the docs - I'm happy to tackle this (perhaps this weekend?) and submit a PR unless someone beats me to it.

That would be awesome! Let me know if there's anything I can help with!

**Comment by eshepelyuk** [comment]
Hello @raboof @orendain  

`protoc` version has nothing to do with this plugin, it is handled by [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin)
`protoc` version override described [here](https://github.com/google/protobuf-gradle-plugin#locate-external-executables)

**Comment by eshepelyuk** [comment]
And all versions are configured via those constants https://github.com/akka/akka-grpc/blob/master/gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPluginExtension.groovy#L10-L14

**Comment by orendain** [comment]
@eshepelyuk Indeed, thanks!  Without docs on how to configure the underlying protobuf plugin, searching for where to make these changes becomes difficult.  Having a page in the docs with some of this info would do wonders.  I had to search the akka-grpc plugin source just to track what versions of the libraries were being used (`./gradlew dependencies` doesn't show deps for plugins, for example) and what plugins to then look up docs for.

**Comment by eshepelyuk** [comment]
FYI, this is a source doc for Gradle plugin

https://github.com/akka/akka-grpc/blob/master/docs/src/main/paradox/buildtools/gradle.md

**Comment by eshepelyuk** [comment]
Partially fixed in #1070

**Comment by raboof** [comment]
> Partially fixed in #1070

I think that note is sufficient :+1: 

After we update the plugin (#1072) I think we can close this issue, agreed?

**Comment by orendain** [comment]
Agreed - thanks for addressing this!  Closing as resolved by #1070 and #1072.
