### ISSUE TITLE
Documentation - Improve Troubleshooting for ALPN failures

### ISSUE THREAD

**Issue by BillyAutrey** [akka/akka-grpc#1095]
### Short description

I suggest that we improve the [troubleshooting page](https://doc.akka.io/docs/akka-grpc/current/troubleshooting.html), specifically for issues regarding this error:
```
Error: io.grpc.StatusRuntimeException: UNAVAILABLE: Failed ALPN negotiation: Unable to find compatible protocol
``` 

There are workarounds/fixes that are not in the documentation.

### Details

Today, if you run `akka-grpc-quickstart-scala` as a server on Java 8 < u251, you will get the following error when running the client:

```
[info] Error: io.grpc.StatusRuntimeException: UNAVAILABLE: Failed ALPN negotiation: Unable to find compatible protocol
[info] Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
```
This is regardless of the Java version used to run the client.  The server's Java version is important here.  Notably, the server itself will NOT report an error of any kind.

The workarounds are as follows:
* Upgrade the server JDK to Java 8 >= u251
* Add [ALPN support manually](https://doc.akka.io/docs/akka-http/10.1/server-side/http2.html#application-layer-protocol-negotiation-alpn-)

I can verify that these solutions work.  We should point to them in the docs, with this error.

**Comment by HarrisonMc555** [comment]
Thank you very much! I couldn't figure out why the getting started steps weren't working for me.

Would it be a good idea to perform a check for the server's Java version at startup? And either report an error or refuse to start if it's Java 8 < u251?

**Comment by raboof** [comment]
> Would it be a good idea to perform a check for the server's Java version at startup?

Hmm, actually we seem to do this at https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2AlpnSupport.scala#L33 - did that not get triggered?

**Comment by HarrisonMc555** [comment]
Interesting! I don't believe I got any such error. This is the output I get from downloading the [`akka-grpc-quickstart-java`](https://developer.lightbend.com/start/?group=akka&project=akka-grpc-quickstart-java) and running:

```bash
$ ./sbt compile
$ ./sbt "runMain com.example.helloworld.GreeterServer"
```

```text
[info] welcome to sbt 1.4.6 (Oracle Corporation Java 1.8.0_211)
[info] loading settings for project akka-grpc-quickstart-java-build from plugins.sbt ...
[info] loading project definition from /Users/myusername/code/akka/akka-grpc-quickstart-java/project
[info] loading settings for project akka-grpc-quickstart-java from build.sbt ...
[info] set current project to akka-grpc-quickstart-java (in build file:/Users/myusername/code/akka/akka-grpc-quickstart-java/)
[info] Compiling 1 protobuf files to /Users/myusername/code/akka/akka-grpc-quickstart-java/target/scala-2.13/akka-grpc/main
[info] Compiling schema /Users/myusername/code/akka/akka-grpc-quickstart-java/src/main/proto/helloworld.proto
protoc-jar: protoc version: 3.11.4, detected platform: osx-x86_64 (mac os x/x86_64)
protoc-jar: embedded: bin/3.11.4/protoc-3.11.4-osx-x86_64.exe
protoc-jar: executing: [/var/folders/ww/p9764btd34d_13297hdw08mm0000gn/T/protocjar9160997046903002481/bin/protoc.exe, --plugin=protoc-gen-jvm_1=/var/folders/ww/p9764btd34d_13297hdw08mm0000gn/T/protocbridge6064805901908345640, --plugin=protoc-gen-jvm_2=/var/folders/ww/p9764btd34d_13297hdw08mm0000gn/T/protocbridge6287833688635627185, --plugin=protoc-gen-jvm_3=/var/folders/ww/p9764btd34d_13297hdw08mm0000gn/T/protocbridge4986394761848355310, --java_out=/Users/myusername/code/akka/akka-grpc-quickstart-java/target/scala-2.13/akka-grpc/main, --jvm_1_out=/Users/myusername/code/akka/akka-grpc-quickstart-java/target/scala-2.13/akka-grpc/main, --jvm_1_opt=flat_package, --jvm_2_out=/Users/myusername/code/akka/akka-grpc-quickstart-java/target/scala-2.13/akka-grpc/main, --jvm_2_opt=flat_package, --jvm_3_out=/Users/myusername/code/akka/akka-grpc-quickstart-java/target/scala-2.13/akka-grpc/main, --jvm_3_opt=flat_package, -I/Users/myusername/code/akka/akka-grpc-quickstart-java/src/main/protobuf, -I/Users/myusername/code/akka/akka-grpc-quickstart-java/target/protobuf_external_src, -I/Users/myusername/code/akka/akka-grpc-quickstart-java/src/main/proto, -I/Users/myusername/code/akka/akka-grpc-quickstart-java/target/protobuf_external, /Users/myusername/code/akka/akka-grpc-quickstart-java/src/main/proto/helloworld.proto]
/Users/myusername/code/akka/akka-grpc-quickstart-java/src/main/protobuf: warning: directory does not exist.
[info] Generating Akka gRPC service interface for [com.example.helloworld.GreeterService]
[info] Generating Akka gRPC Client [com.example.helloworld.GreeterService]
[info] Generating Akka gRPC Lifted Client interface[com.example.helloworld.GreeterService]
[info] Generating Akka gRPC service handler for com.example.helloworld.GreeterService
[info] running com.example.helloworld.GreeterServer
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
gRPC server bound to: /127.0.0.1:8080
```

**Comment by raboof** [comment]
> I don't believe I got any such error

There were 2 parts to this problem:
- logging was broken (https://github.com/akka/akka-grpc-quickstart-java.g8/pull/50)
- it was using Akka HTTP 10.1.13, but the nicer error message wasn't introduced until 10.2.2. I think we should update the quickstart to the latest Akka HTTP version (https://github.com/akka/akka-grpc-quickstart-java.g8/pull/51)

**Comment by raboof** [comment]
both improvements seem to be applied since
