### ISSUE TITLE
Akka gRPC maven plugin not generating files in outputDirectory

### ISSUE THREAD

**Issue by venkateshzifo** [akka/akka-grpc#1104]
### Versions used 
1.0.1

`<plugin> <groupId>com.lightbend.akka.grpc</groupId> <artifactId>akka-grpc-maven-plugin</artifactId> <version>${akka.grpc.version}</version> <configuration> <language>Java</language> <outputDirectory>${akka-grpc.outputDirectory}</outputDirectory> <extraGenerators>play.grpc.gen.javadsl.PlayJavaServerCodeGenerator</extraGenerators> <generateClient>true</generateClient> <generateServer>true</generateServer> <generatorSettings></generatorSettings> </configuration> <executions> <execution> <goals> <goal>generate</goal> </goals> </execution> </executions> </plugin>
`
### Expected Behavior
Expected to generate java files inside src/main/java 

### Actual Behavior
Always generating inside target/generated-sources
Please provide a description of what actually happens, working from the same starting point.

**Comment by ihostage** [comment]
Isn't it resolved in https://github.com/akka/akka-grpc/pull/1100? 🤔 
`outputDirectory` configurable now.

**Comment by raboof** [comment]
Yes looks like it!
