### ISSUE TITLE
Let the sbt plugin expose the versions of the `io.grpc` libraries

### ISSUE THREAD

**Issue by ennru** [akka/akka-grpc#1125]
When projects pull in other `io.grpc` libraries (such as `"io.grpc" % "grpc-auth"`) they need to align with the version Akka gRPC uses.
The alignment can be achieved easier if the Akka gRPC sbt plugin exposes the versions of the libries it requires.

**Comment by raboof** [comment]
(while we're at it expose our 'own' version in code as well, https://github.com/playframework/play-grpc/blob/master/project/Dependencies.scala#L17)

**Comment by raboof** [comment]
This information is already available through `akka.grpc.gen.BuildInfo`
