### ISSUE TITLE
The generated java sources are not compiled when a project has only kotlin sources

### ISSUE THREAD

**Issue by symphonata** [akka/akka-grpc#1128]
### Versions used 

akka-grpc gradle plugin 1.0.2

Akka version: 

2.6.9

### Expected Behavior

Do not skip the compileJava task

### Actual Behavior

Skipping task ':compileJava' as task onlyIf is false

### Relevant logs

Skipping task ':compileJava' as task onlyIf is false

**Comment by ignasi35** [comment]
@symphonata IIUC, this happens on a Gradle build where all the code-source is Kotlin? (I'm trying to narrow down the scope).

Do you have a reproducer public?

**Comment by symphonata** [comment]
Yes, and it seems this issue fix #1056 is the cause. You can reproduce it by creating a simple gradle project like this [repoducer](https://github.com/symphonata/akkaGrpcGradlePluginIssue)

**Comment by ihostage** [comment]
Resolved in #1308 and can be closed.

**Comment by raboof** [comment]
Thanks!
