### ISSUE TITLE
Add TE: trailers header

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#1173]
grpc-java suggests:

```
WARNING: Expected header TE: trailers, but null is received. This means some intermediate proxy may not support trailers
```

I suspect we can just add that header as a default header to the client, but we should double-check that with the spec.

**Comment by ignasi35** [comment]
From [the spec](https://httpwg.org/specs/rfc7540.html#n-connection-specific-header-fields):

>The only exception to this is the TE header field, which MAY be present in an HTTP/2 request; when it is, it MUST NOT contain any value other than "trailers".

So I think we can hard-code it so it's always included and set to `"trailers"`.

**Comment by ignasi35** [comment]
Refs https://github.com/akka/akka-http/pull/3616
