### ISSUE TITLE
Review byte[] to ByteString to byte[] conversions

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-grpc#1180]
Building the Serialization and Marshalling abstractions hid some conversions from `byte[]` to `ByteString` or `ByteBuffer` and back.

For example, in `ProtoMarshaller` there's:

```
// u: ProtobufSerializer[T]
u.deserialize(akka.util.ByteString(baos.toByteArray))
```

and then on `ScalapbProtobufSerializer` we do:

```
  override def deserialize(bytes: ByteString): T =
    companion.parseFrom(CodedInputStream.newInstance(bytes.asByteBuffer))
```

where `CodedInputStream.newInstance(...)` already provides an overload for `byte[]` (so we can avoid the `ByteString` and the `ByteBuffer` instances).

**Comment by viktorklang** [comment]
To avoid unnecessary copying, you might want to do:

```scala
// u: ProtobufSerializer[T]
u.deserialize(akka.util.ByteString.fromArrayUnsafe(baos.toByteArray))
```

**Comment by ignasi35** [comment]
> To avoid unnecessary copying, you might want to do:
> 
> ```scala
> // u: ProtobufSerializer[T]
> u.deserialize(akka.util.ByteString.fromArrayUnsafe(baos.toByteArray))
> ```

Thanks @viktorklang! 

IIUC, that would save a copy of the byte array but still allocate a `ByteString` and a `ByteBuffer`.

**Comment by ignasi35** [comment]
I just noticed `CodedInputStream.newInstance` also has an overload that takes an `InputStream` which is what `Marshaller#parse` receives.

So, in order to turn an `InputStream` into a `T` the current code in `Marshaller` combined with `ScalapbProtobufSerializer` does the following:

 - read the `InputStream` into memory as a `byte[]`
 - create a copy of the `byte[]` when creating a `ByteString`
 - create a `ByteBuffer` from the `ByteString`
 - create a `CodedInputStream` from that

Instead, we could try what performance impact (if any) the following had:

 - create a `CodedInputStream` from `InputStream`

And see if this approach, as opposed to the current abstraction, pays off.

It's a trade-off. 🤷🏼‍♂️

**Comment by raboof** [comment]
> Instead, we could try what performance impact (if any) the following had

Definitely worth an experiment - though there's a chance that this method is indeed actually inefficient, see #1163

**Comment by viktorklang** [comment]
👍--
Cheers,
√

**Comment by lomigmegard** [comment]
I looked at this issue, my conclusions are:
- Using `ByteString.fromArrayUnsafe` is a safe quick-win, PR is open #1281
- The `ProtobufSerializer` API should probably be extended to allow parsing from an `InputStream`. The downstream implementations (GoogleProtobuf or ScalaPB) have methods for streams and should be leveraged where possible. I think the above suspicion of inefficient parsing should be handled separately.
- Not really related, but the `GoogleProtobufSerializer` usage of reflexion can be avoided by passing the `Parser` directly to the class. I will open another issue if maintainers don't foresee problems with changing its constructor signature.

**Comment by raboof** [comment]
>     * Using `ByteString.fromArrayUnsafe` is a safe quick-win, PR is open #1281

:+1: thanks!

>     * Not really related, but the `GoogleProtobufSerializer` usage of reflexion can be avoided by passing the `Parser` directly to the class. I will open another issue if maintainers don't foresee problems with changing its constructor signature.

We do want to be binary compatible in the public API's and the API's used by the generated code, but this sounds like a change that probably could be done in a binary-compatible way, so :+1:
