### ISSUE TITLE
GoogleProtobufSerializer should not use reflexion

### ISSUE THREAD

**Issue by lomigmegard** [akka/akka-grpc#1285]
### Short description

The `GoogleProtobufSerializer` wrapper currently takes a `Class[_ <: com.google.protobuf.Message]` as argument. It then uses reflection to call the `parseFrom()` static method. This is not a good practice, and Protobuf generated messages have a `Parser` class for this use-case.

### Details

The constructor is used in generated Java sources, but there is a path for binary compatibility. I suggest changing the main constructor to take a `com.google.protobuf.Parser` instead, with a auxiliary constructor to keep backward compatibility.

The rationals for this change are good practices, future improvements that could root from having a `Parser` on-hand, and marginal performance gain.

We can discuss the impacts in the coming PR.

**Comment by viktorklang** [comment]
Sounds like a good idea, @lomigmegard!
