### ISSUE TITLE
sbt plugin doesn't generate java's PowerApi interface

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-grpc#1289]
When using sbt for a Java gRPC project, the plugin doesn't generate the `ServiceNamePowerApi` interface file. Using Maven or Gradle the `ServiceNamePowerApi` interface is generated.

### Expected Behavior

`sbt compile` produces a `ServiceNamePowerApi` interface.

### Actual Behavior

`target/scala-2.13/akka-grpc/main/com/package/ServiceNamePowerApi.java` is not generetad

### Reproducible Test Case

```
sbt new  akka/akka-grpc-quickstart-java.g8
cd akka-grpc-quickstart-java
sbt compile
```

**Comment by ignasi35** [comment]
I should read the docs before posting a new issue.

It all works as expected when I add the [required setting](https://doc.akka.io/docs/akka-grpc/current/buildtools/sbt.html#generating-server-). 🤦🏼‍♂️

**Comment by raboof** [comment]
does that mean the default setting is inconsistent between maven/grade/sbt?
