### ISSUE TITLE
Run the latest jdk8 on CI

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#1332]
Between 1.8.0_275 and 1.8.0_292, apparently `PBEWithSHA1AndDESede` is no longer available, which causes a problem running the integration tests 

Let's just run the integration tests on 1.8.0_275 for now, and move back to the latest version when this is resolved upstream (either in the JDK or in the integration test infra)

See also: https://bugs.openjdk.java.net/browse/JDK-8228481

**Comment by jrudolph** [comment]
Here's another related JDK bug issue:

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8266261

Also related issue with workarounds: https://github.com/corretto/corretto-8/issues/306

**Comment by mkurz** [comment]
Seems like this should get fixed with the next JDK July release.

**Comment by jrudolph** [comment]
Good to know, this was quite annoying...

**Comment by raboof** [comment]
We use 'latest' JDK versions since the move to GitHub actions
