### ISSUE TITLE
Make sure things work for users on Windows

### ISSUE THREAD

**Issue by ktoso** [akka/akka-grpc#136]
We can also set up CI on windows using https://www.appveyor.com/

**Comment by ktoso** [comment]
If it does not work to _develop_ akka-grpc on windows that's a nasty but a lesser problem; we do need to make sure people can use it on windows though

**Comment by johanandren** [comment]
I'll see if I can get a virtual machine with windows to try this.

**Comment by ktoso** [comment]
https://www.parallels.com/ gets you a windows trial right away (and installs automatically), you can try that

**Comment by johanandren** [comment]
Verified on Windows 10 that the plugins for both sbt and maven works, and that a client can interact with a server.

Tried building on windows as well but failed on sbt-git not finding git (even though it was on the path) and couldn't get the jGit support in the plugin to work, as that wasn't the primary goal I'm leaving it at that.

**Comment by ktoso** [comment]
Sounds great. Good enough to complete this task I believe :) Thanks!
