### ISSUE TITLE
Using Scala 2.13 artifacts with Scala 3

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#1396]
Generally it should be possible to use Scala 2.13 artifacts in Scala 3 projects.

However, when using Akka gRPC in a Scala 3 project via the sbt plugin, the dependency on the runtime library is not correctly added: when deciding which version of the runtime library to add, Akka gRPC automatically adds the one for the 'current' Scala version (https://github.com/akka/akka-grpc/blob/master/sbt-plugin/src/main/scala/akka/grpc/sbt/AkkaGrpcPlugin.scala#L200-L210), while in this case it should use the sbt `.cross()` feature to use the 2.13 library on Scala 3.

Perhaps we should give the runtime library its own sbt key, so at least it can be overridden?

**Comment by RomanLebid** [comment]
There's a workaround for this issue that worked for us by adding 
`inConfig(Compile)(scalaBinaryVersion := "2.13")`

And that works alright for generating server code, but clients fail to compile
I assume that's different because of compiler changes related to type inference
```
32 |  private val clientState = new ClientState(settings, akka.event.Logging(sys.classicSystem, this.getClass))
   |                                                                                                          ^
   |Cannot find LogSource for Class[? <: grpc.health.v1.DefaultHealthClient] please see ScalaDoc for LogSource for how to obtain or construct one..
   |I found:
   |
   |    akka.event.LogSource.fromAnyClass[Nothing]
   |
   |But method fromAnyClass in object LogSource does not match type akka.event.LogSource[Class[? <: grpc.health.v1.DefaultHealthClient]].
```

**Comment by RomanLebid** [comment]
Yeah, something has definitely change around existential types

Was only able to compile clients, by not generating them, copying the source code and changing this line
https://github.com/akka/akka-grpc/blob/e6f0402e4eab6ab87bba970cb0c4674b881f13cf/codegen/src/main/twirl/templates/ScalaClient/Client.scala.txt#L50
to using the actual class and not the class of current instance
```
private val clientState = new ClientState(settings, akka.event.Logging(sys.classicSystem, classOf[DefaultHealthClient]))
```

**Comment by raboof** [comment]
Surprising, but seems like a fine workaround - would you like to PR it?

**Comment by johanandren** [comment]
That's the same workaround for that we've been doing on the Akka side, so I think it is good.

**Comment by RomanLebid** [comment]
> Surprising, but seems like a fine workaround - would you like to PR it?

Yes, I think I'll make a PR for this issue

One more issue I've found is that if gRPC service has multiple methods, then indentation is preserved from the [template](https://github.com/akka/akka-grpc/blob/master/codegen/src/main/twirl/templates/ScalaClient/Client.scala.txt) and lifted versions of methods are shifted to the right a little, thus breaking the compilation

```
69 |      override def call(): SingleResponseRequestBuilder[grpc.health.v1.HealthCheckRequest, grpc.health.v1.HealthCheckResponse] =
   |      ^
   |      Line is indented too far to the right, or a `{` is missing before:
```

**Comment by raboof** [comment]
Thanks for #1403, merged!

I wonder if we could make a 'scripted' test that verifies things keep working with Scala 3 before closing this issue.
