### ISSUE TITLE
Publish the akka-grpc-codegen package for Scala 2.13

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#1400]
It looks like we lost this in 18bcff9359f2ff4ac58a944c4a0f5e09270e82c5

**Comment by bmo-at** [comment]
Any advancement on this? Or alternatively a workaround on how I can build 2.13 artifacts locally?

**Comment by raboof** [comment]
I'm afraid not - possibly the changes in #1516 might help for this, but I ran into other problems there. Help welcome!

**Comment by raboof** [comment]
> Or alternatively a workaround on how I can build 2.13 artifacts locally?

That you can do with `sbt ++2.13.8 akka-grpc-codegen/publishLocal`

**Comment by bmo-at** [comment]
Ah well you see, I am not using sbt. I'm trying out mill today. I am currently in the process of exploring if I can migrate my "legacy" play-akka-grpc enpoint application to mill.
I am also trying to make use of [this plugin](https://github.com/tjarvstrand/mill-akka-grpc/), but development seems to have been abandoned and I am unsure whether it is worth investing significant time.

**Comment by bmo-at** [comment]
But thank you for all the pointers anyway and the fast response!

**Comment by bmo-at** [comment]
Ok, so that was a pretty stupid comment of me to make I realize now. I cloned the akka-grpc repo and used the local publishing to at least get a copy into my ivy2 cache that is 2.13 scala and 2.1.4 akka-grpc.
This at gets me a chance to work on the aforementioned plugin.
Maybe I can contribute back if the maintainer is still active/

**Comment by raboof** [comment]
> Ok, so that was a pretty stupid comment of me to make I realize now.

No worries ;)

> I cloned the akka-grpc repo and used the local publishing to at least get a copy into my ivy2 cache that is 2.13 scala and 2.1.4 akka-grpc. This at gets me a chance to work on the aforementioned plugin.

Great! In the mean time I also added a workaround so now we publish snapshots to https://oss.sonatype.org/content/repositories/snapshots/com/lightbend/akka/grpc/akka-grpc-codegen_2.13 - and I *think* this should work for 2.1.5 as well

> Maybe I can contribute back if the maintainer is still active/

Would be great!

Let's close this for now and re-open if it turns out publishing for 2.1.5 didn't work after all.
