### ISSUE TITLE
How to deploy akka-grpc on AWS with ELB

### ISSUE THREAD

**Issue by GOODDAYDAY** [akka/akka-grpc#1424]
Hi there:
  
  * There is a trouble that I want to deploy my akka-gRPC Application on AWS. It is ok that gRPC client connect to server directly.
  * Now I want to put an ELB between them. This is [AWS ELB doc](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html).It shows that no matter http2/grpc protocol. It need my akka-gRPC Application support HTTPS. [serve-grpc-over-https](https://doc.akka.io/docs/akka-grpc/current/deploy.html#serve-grpc-over-https) shows that I need to build a `SSLContext` to support HTTPS. But private dns in AWS can not download cmkey or CA or others. So I can not build `SSLContext`. 
  * In my mind, SSL action will occur in client and ELB. ELB will forward request to server. In this word, HTTPS is only useful for health check?
  * Is there something wrong Or anything I need to do with ELB?

Regards,
Goody

**Comment by raboof** [comment]
We try to use issues for bugs and feature requests. Since this is more of a discussion topic, https://discuss.akka.io might be a better place for this, could you open this there? I haven't worked with ELB's in a while myself though, so I can't answer this question off the top of my head.

**Comment by GOODDAYDAY** [comment]
Ok, thank you for your replying!
