### ISSUE TITLE
When can I use akka-grpc with scala 3?

### ISSUE THREAD

**Issue by BaekGeunYoung** [akka/akka-grpc#1436]
I saw some issues about using akka-grpc with scala 3:
#1403 
#1396 

And it seems that this PR was merged, but not released yet. When can I use the new version of akka-grpc, including this PR?
If new release is not planned for the foreseeable future, is there any workaround method which I can apply?

**Comment by raboof** [comment]
You can always use the latest version by getting a snapshot from https://oss.sonatype.org/content/repositories/snapshots/com/lightbend/akka/grpc/

There's a v2.1.0-M1 tag but I haven't checked if those two improvements are in there - I *think* so.

Let's try to do a 2.1.0 next week.

**Comment by BaekGeunYoung** [comment]
thank you for answering. Then I will temporarily use the recent snapshot version, until stable 2.1.0 is released. Thank you!

**Comment by raboof** [comment]
2.1.0 is now out, so I think we can close this issue. Thanks for the ping!
