### ISSUE TITLE
(wrong repo) Richer types for generated code

### ISSUE THREAD

**Issue by richdougherty** [akka/akka-grpc#150]
In order to consume the generated code downstream, it would be easier if the code had predictable types. This would make it easier for us to load code via reflection and then cast it.

Examples: https://gist.github.com/richdougherty/0a4d2124bff7a1a9db1676e5b4d92a05

**Comment by raboof** [comment]
We should definitely add them wherever they can help. As I'm not so familiar with Play it's hard for me to predict where they'll be useful and what they should look like - perhaps add them on an as-needed basis while we figure out what play-grpc should look like?

**Comment by richdougherty** [comment]
I've added a factory type for the gRPC client in #356. Let's close this ticket now.
