### ISSUE TITLE
Use M1 compatible version of protoc / sbt-protoc

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-grpc#1501]
See https://discuss.lightbend.com/t/the-grpc-quickstart-does-not-compile/9124

It seems the quickstart won't run on M1 because of missing support for aarch64 of protoc. It seems using a newer version of protoc might fix that problem.

See also https://github.com/thesamet/sbt-protoc/pull/269

**Comment by johanandren** [comment]
Should be fixed by #1490

**Comment by johanandren** [comment]
Also, duplicate of #1238

**Comment by jrudolph** [comment]
Yep, sorry.
