### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#151]
We've discussed before (e.g. #67) that we should introduce our own Configuration classes for the client, to configure things like host/port, TLS, compression, authentication etc. 

It would also be useful to be able to easily consume configuration from a `io.grpc.CallCredentials` into this configuration (#87).

Since a gRPC client is generated for each specific protocol, this configuration is probably usually more 'static' compared to more general-purpose clients such as HTTP. For this reason it probably makes sense to make it easy to load the configuration from typesafe-config. That could look something like:

```
akka.grpc.client {
  "grpc.testing.TestService" = {
    # ...
  }
}
```

In play-grpc we could even use this configuration to be able to generate a client configured with these settings and make it available for easy injection.

**Comment by ktoso** [comment]
I would propose having globbing in the selector season as well as “include-feature = on” for enabling more powerful things so one can do it selectively

**Comment by raboof** [comment]
Done in #254
