### ISSUE TITLE
Improve serverReflectionInfo response time

### ISSUE THREAD

**Issue by github-samuel-clarenc** [akka/akka-grpc#1528]
## Short description 

The server reflection can be long for large proto files. 

## Details 

The [ServerReflectionImpl.serverReflectionInfo](https://github.com/akka/akka-grpc/blob/main/runtime/src/main/scala/akka/grpc/internal/ServerReflectionImpl.scala#L35) can be relatively long to execute, depending on the proto size. This is mainly due to the execution of [AbstractMessageLite.toByteString](https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/AbstractMessageLite.java#L56) which is called each time. 

## Solution proposal

We could introduce a simple `Map` to cache the proto as a ByteString to avoid calling `toByteString` every time.

**Comment by raboof** [comment]
Sounds reasonable to me - would you be up for creating a PR?

**Comment by github-samuel-clarenc** [comment]
> Sounds reasonable to me - would you be up for creating a PR?

Sure, I'm currently working on it (and checking that we can gain something with the jmh benchmarks!)
