### ISSUE TITLE
Indentation is not preserved in paradox

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#153]
The example (inline) maven XML indentation does not seem to be preserved. This does not come from a snippet because it contains version numbers from the build.

**Comment by ennru** [comment]
I'm not sure which XML this was about, but [this page](https://doc.akka.io/docs/akka-grpc/current/buildtools/maven.html) looks OK to me. Close?

**Comment by raboof** [comment]
Looks OK to me indeed
