### ISSUE TITLE
Select client/server/both

### ISSUE THREAD

**Issue by 2m** [akka/akka-grpc#155]
https://github.com/akka/akka-grpc/pull/154#discussion_r179753307

**Comment by 2m** [comment]
I think this is a concern in the sbt plugin as well. Currently it is possible to select what to generate, but requires configuring multiple settings to achieve the desired result. We need something more user friendly to select from the `{java,scala} x {client,server}`.

**Comment by patriknw** [comment]
@raboof is this done?

**Comment by raboof** [comment]
java/scala switching is in there, but client/server/both switching not yet (it currently defaults to 'both').

**Comment by patriknw** [comment]
What is the reason for having a `Seq` for `akkaGrpcGeneratedLanguages`? Doesn't make much sense to generate both java and scala, since class names will be conflicting?

**Comment by raboof** [comment]
If you disable the `flat_package` option the class names no longer conflict. This seems like it could be convenient in some cases (for example we use this in the interop testing project)

**Comment by patriknw** [comment]
ok, then there is a valid reason

**Comment by patriknw** [comment]
seems like the gradle plugin puts the message files in wrong directory: plugin-tester-scala/build/generated/source/proto/main/scalapb/example/myapp/helloworld/grpc/HelloReply.scala

The service classes are right.

**Comment by patriknw** [comment]
ah, it's `scalapb` vs `akkaGrpc`
(I was expecting everything together)
