### ISSUE TITLE
Documentation/getting started improvements - Scala/sbt

### ISSUE THREAD

**Issue by johanandren** [akka/akka-grpc#158]
This is what I found/had problems/questions about with when starting from zero on the Scala side of things, a bit unfocused but I guess we can split of separate tickets as needed later.

## Server

* What does java_package in the .proto-file do? I played around with it a bit and couldn't see that it makes a difference, even removing it worked fine, remove it from the sample or at least provide a comment explaining?
* Question of taste: do we recommend the `MyService` + `MyServiceImpl` naming style (I think I'd personally would prefer `MyServiceApi` and `MyService`)?
* We should document extra that it must be bound using Http2 (as it binds fine with Http 1 but doesn't work and gives weird errors) and that the ALPN agent is needed for that.

## Client

* What about lifecycle, should it be managed, does it need to be stopped?
* Does it keep connections alive, what happens if those break, does it reconnect automagically, do I need to care?
* Should I create a new one for every call or reuse a single one for all calls, is it thread safe?

## General

* Sharing .proto-files through an artifact or copying. Should we list some pro's/con's or simply recommend a versioned artifact when all involved parts are JVM for example?
* Should we say something about structuring a larger/more complex service? Should one prefer having a single gRPC API or multiple ones?

**Comment by patriknw** [comment]
> Question of taste: do we recommend the MyService + MyServiceImpl naming style (I think I'd personally would prefer MyServiceApi and MyService)?

Yeah, tasty. I prefer MyService + MyServiceImpl. Isn't that the most common java style of such things?

**Comment by raboof** [comment]
We used to append `Service` to the service name defined in the `proto`, but that lead to `TestServiceService`, so we dropped that ;). Perhaps the chance of a `FooApiApi` is smaller, but it seems safer to leave the service name from the contract untouched?

**Comment by patriknw** [comment]
We should not add something automatically. I think this was only about what convention we would use in the examples.

**Comment by raboof** [comment]
Ah - there I'm fine with either, but in the `TestService` case this is something that is also used upstream (https://github.com/grpc/grpc-java/blob/master/interop-testing/src/main/proto/io/grpc/testing/integration/test.proto) so it makes sense to follow that convention?

**Comment by johanandren** [comment]
Ok! No strong feelings on that one, I guess one can argue either way, just wanted to make sure it was thought through. Maybe we should explicitly note in the docs what names of things get generated etc. even if that is also shown in the source samples.

**Comment by raboof** [comment]
Server:
* [x] Now documented at https://github.com/akka/akka-grpc/blob/master/docs/src/main/paradox/proto.md#code-generation-options
* [ ] Let's consistently show `FooServiceApi`/`FooService` in our examples, except for examples that come from an external source.
* [x] For now the docs at https://github.com/akka/akka-grpc/blob/master/docs/src/main/paradox/server.md should probably be sufficient? Beyond that we should consider #180 and https://github.com/akka/akka-http/issues/1987

Client:
* [x] Good question, let's start with a client that needs to be closed by whoever creates it, and then see if we can add convenient wrappers that feel native for Akka, Play and Lagom (could be multiple)
* [ ] Let's answer these questions and add that to the docs
* [ ] You should be able to use a client for many concurrent calls, let's document this.

General:
* [ ] We currently show the "copy your .proto" method first and document how to get it via an artifact second. I'm not sure we have a particular approach to recommend.
* [ ] Would be good to have a 'design' section in the docs, and also link to https://cloud.google.com/apis/design/design_patterns

**Comment by ktoso** [comment]
>  We currently show the "copy your .proto" method first and document how to get it via an artifact second. I'm not sure we have a particular approach to recommend.

Yes I think that's fine. It shows "completely decoupled, no deps, no nothing". The second one can accidentally be abused, and in general better to show the "what it does" and then "well, you could do some shortcuts" in this case I think

**Comment by johanandren** [comment]
I think we should describe pros and cons with the respective ones:
 * jar-artifact - great for Java only shops, makes sure you get versioning right through release/publish
 * just proto file - great if you have non-java consumers, you have to figure out versioning yourself

**Comment by raboof** [comment]
I'm not sure I'd recommend jar-artifact for JVM-only shops either though...

* as you say it needs to be a separate artifact with no other dependencies, so it'll make build processes more complicated
* people will be tempted to turn it into a 'client library'
* you'll still have to decide whether to version the proto artifact together with the server project (which means server updates that don't change the API will anyway cause a new version of the API artifact) or separately (which will probably introduce some more overhead in the build infrastructure)

Seems like relatively heavy. When combined with additional tooling and guidance (like in Lagom I guess?) it could make sense though.

**Comment by raboof** [comment]
(tried out `GreeterServiceApi` as service name, but that leads to things like `GreeterServiceApiClient` and `GreeterServiceApiHandler` - seems nicer to do `GreeterService` and `GreeterServiceImpl`, `GreeterServiceClient`, etc)

**Comment by ktoso** [comment]
> people will be tempted to turn it into a 'client library'

Yeah that's the scariest bit -- and then you're back again to coupling them. So all in all, the copy pasta is seen OK for these things I believe -- better than coupling at least

**Comment by raboof** [comment]
I think we covered all feedback in this PR now, let's close this one and if we missed anything open separate tickets
