### ISSUE TITLE
akka-grpc-maven-plugin compile fail

### ISSUE THREAD

**Issue by wang287611200** [akka/akka-grpc#1591]
hello, I use Akka grpc maven plugin(akka-grpc-maven-plugin ) on study  akka-platform-guide(https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/index.html) is wrong.

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/3919800/157804224-58fe27ad-1adf-4cfe-9e01-3d2d2941ca04.png">

**Comment by raboof** [comment]
Thanks for sharing! I downloaded https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/_attachments/0-shopping-cart-start-java.zip and did `mvn compile` in the `shopping-cart-service` project, that seemed to work fine.

From the screenshot you posted it looks like perhaps it tried to download protoc.exe, but instead it somehow downloaded an HTTP 301 redirect page. It seems to work here, though. If you run with `mvn -X compile -f out.txt`, do you get any logging describing where it gets the protoc executable from?

**Comment by wang287611200** [comment]
Thanks for your answer.I forget to say that i use MacOS M1 （it's darwin/arm64 platform）

**Comment by wang287611200** [comment]
I  found   it will download com/google/protobuf/protoc/ maven-metadata.xml  when the project execute akka-grpc-maven-plugin,but the file is wrong.

**Comment by raboof** [comment]
> I found it will download com/google/protobuf/protoc/ maven-metadata.xml

What is the full url? I think some parts are missing here

> <img alt="image" width="437" src="https://user-images.githubusercontent.com/3919800/158530718-ff069f8e-1300-402f-a398-79baba6e90d1.png">

Hmm, I don't think Maven Central is using Tengine - do you have a proxy in between? Perhaps the problem is the proxy uses 301, and Maven usually follows 301's, but (and this is just guessing) perhaps https://github.com/os72/protoc-jar/blob/master/src/main/java/com/github/os72/protocjar/Protoc.java#L318 does not follow redirects?

**Comment by wang287611200** [comment]
> 

yes,This is the maven mirror proxy wrong.i build success after. delete the files  (~/.m2/setting.xml and /var/folders/3y/wmzfgdmx0h1_1mmpmvzt6thh0000gn/T/protocjar.webcache/com/google/protobuf/protoc )

**Comment by wang287611200** [comment]
Thanks for you answer :)

**Comment by raboof** [comment]
Glad you were able to find the problem and fix it!
