### ISSUE TITLE
Publish 2.13 Codegen on Maven

### ISSUE THREAD

**Issue by mpdn** [akka/akka-grpc#1655]
The Maven repo seems to only have 2.12 codegen versions: https://mvnrepository.com/artifact/com.lightbend.akka.grpc/akka-grpc-codegen

It is published on Sonatype though: https://oss.sonatype.org/#nexus-search;gav~com.lightbend.akka.grpc~akka-grpc-codegen_2.13~~~~kw

But having it on Maven would be useful as well.

**Comment by mpdn** [comment]
Actually, I see that only codegen 2.15 has been published as scala 2.13 to sonatype, so maybe once 2.15 is published to maven that will also be available as 2.15 as well?

**Comment by mpdn** [comment]
Welp, turns out that mvnrepository.com is just showing an old, cached page and 2.1.5 is actually released on Maven, which does indeed support Scala 2.13. So everything works. :D

**Comment by raboof** [comment]
thanks for checking and closing!
