### ISSUE TITLE
Ability to handle rpc functions named close

### ISSUE THREAD

**Issue by benthecarman** [akka/akka-grpc#1667]
### description

I am trying to use a proto file that has a rpc function named close. This overlaps with the akka grpc function also called close so it cannot compile. Ideally it should rename to something else.

**Comment by raboof** [comment]
Good observation!

I think we should probably change the generated method name. Eventually it would be great if we could allow users to configure various aspects of code generation on the method level, then they could resolve this naming clash themselves (#451). Until that time we could treat 'close' as a special case and rename it automatically - perhaps adding some suffix? Would you be interested in contributing this feature?

**Comment by benthecarman** [comment]
> Would you be interested in contributing this feature?

I would love to but not too sure how to do it. Willing to provide a small bitcoin bounty for the feature :)

**Comment by benthecarman** [comment]
I think I was able to do it here: https://github.com/akka/akka-grpc/pull/1670

**Comment by raboof** [comment]
Awesome, thanks!
