### ISSUE TITLE
Ability to add a client certificate to a request

### ISSUE THREAD

**Issue by benthecarman** [akka/akka-grpc#1676]
I have a `client.pem` certificate that I need to use when making a grpc request to the server, otherwise I cannot make any requests. It doesn't seem like there is a way to add this to the requests currently.

context: https://github.com/ElementsProject/lightning/issues/5280#issuecomment-1136625285

**Comment by johanandren** [comment]
Not much documentation around using a .pem but I think this is what the quickstart projects do, so create a project from either of those templates and take a look at the client bootstrap and application.conf file there (https://doc.akka.io/docs/akka-grpc/current/getting-started.html#akka-grpc-quickstart ).

**Comment by benthecarman** [comment]
Ah, is there a way to set the `.pem` file dynamically instead of having the path hard coded in the conf file

**Comment by johanandren** [comment]
You can construct the conf-block dynamically through the Config lib APIs, possibly also directly APIs on `GrpcClientSettings` (lots of TLS/SSL related `with`-methods there) but I don't know for sure from the top of my head.

**Comment by benthecarman** [comment]
Ah yeah you can do with with `SSLContextUtils.trustManagerFromStream(stream)` and `withTrustManager(_)`
