### ISSUE TITLE
Failed: NonBalancingIntegrationSpecAkkaHttp

### ISSUE THREAD

**Issue by johanandren** [akka/akka-grpc#1711]
https://github.com/akka/akka-grpc/actions/runs/3461767253/jobs/5779790575#step:5:6504

```
[info] - should send requests to a single endpoint that is restarted in the middle *** FAILED *** (246 milliseconds)
[info]   62 was not equal to 100 (NonBalancingIntegrationSpec.scala:96)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:407)
[info]   at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6778)
[info]   at org.scalatest.matchers.should.Matchers.should(Matchers.scala:6823)
[info]   at org.scalatest.matchers.should.Matchers.should$(Matchers.scala:1808)
[info]   at akka.grpc.scaladsl.NonBalancingIntegrationSpec.should(NonBalancingIntegrationSpec.scala:33)
[info]   at akka.grpc.scaladsl.NonBalancingIntegrationSpec.f$proxy2$1(NonBalancingIntegrationSpec.scala:96)
[info]   at akka.grpc.scaladsl.NonBalancingIntegrationSpec.$init$$$anonfun$1$$anonfun$2(NonBalancingIntegrationSpec.scala:68)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka-grpc/actions/runs/3525784747/jobs/5912931128#step:5:6323

**Comment by johanandren** [comment]
https://github.com/akka/akka-grpc/actions/runs/3526228899/jobs/5913907347#step:5:6441

**Comment by johanandren** [comment]
https://github.com/akka/akka-grpc/actions/runs/3583408086/jobs/6028798735#step:5:6405

**Comment by johanandren** [comment]
https://github.com/akka/akka-grpc/actions/runs/3681671502/jobs/6228594973

**Comment by patriknw** [comment]
https://github.com/akka/akka-grpc/actions/runs/3754393400/jobs/6378573366

**Comment by octonato** [comment]
https://github.com/akka/akka-grpc/actions/runs/3784643666/jobs/6434095059#step:5:8929

**Comment by octonato** [comment]
https://github.com/akka/akka-grpc/actions/runs/3804340546/jobs/6471472387#step:5:6395

**Comment by johanandren** [comment]
https://github.com/akka/akka-grpc/actions/runs/3834626928/jobs/6527186341#step:5:6451
