### ISSUE TITLE
Quickstart/sample projects

### ISSUE THREAD

**Issue by johanandren** [akka/akka-grpc#172]
Maybe we should also publish a maven archetype that has the right directories and the plugin already enabled? Can those possible be part of the plugin artifact maybe even?

**Comment by patriknw** [comment]
Isn't it better to have a sample project in the same way as other Quickstarts (in Akka)?

**Comment by raboof** [comment]
I wonder if we could publish sample projects both as techhub quickstarts and maven artifacts at the same time.

Until that time either would be fine, and a sample/quickstart project might be more suitable

**Comment by johanandren** [comment]
Quickstart may be a better way. Just that we need to remember to make one quickstart per build tool (for the language they make sense) then.

**Comment by raboof** [comment]
For Lagom we'd want a 'simple' quickstart example and a 'more interesting' one such as an adaptation of the auction example (just replacing one service-to-service call)

**Comment by patriknw** [comment]
Tasks:
* [ ] Akka gRPC Quickstart with Java
* [ ] Akka gRPC Quickstart with Scala
* [ ] Play gRPC Quickstart with Java
* [ ] Play gRPC Quickstart with Scala
* [ ] Lagom gRPC Quickstart with Java
* [ ] Lagom gRPC Quickstart with Scala

All those can contain sbt/maven/gradle builds and instructions (not gradle for Lagom, not maven for Play)

**Comment by patriknw** [comment]
Created a separate ticket https://github.com/akka/akka-grpc/issues/283 for the online auction to keep this focused on the quickstarts.

**Comment by patriknw** [comment]
First proposal of Akka gRPC Quickstart with Scala in https://github.com/akka/akka-grpc-quickstart-scala.g8/pull/1
Let's review and polish thoroughly before translating to the other variants.

**Comment by patriknw** [comment]
I have completed the "Akka gRPC Quickstart with Scala" in https://github.com/akka/akka-grpc-quickstart-scala.g8

Putting the ticket back to the TODO list since I will not work on the other parts

**Comment by johanandren** [comment]
Started working on the play samples in #301

**Comment by chbatey** [comment]
I'll take a look at the java akka grpc sample that Johan started

**Comment by dwijnand** [comment]
Updated @patriknw checklist.  I think progress for these should be tracked in those repos.
