### ISSUE TITLE
Client using netty backend cannot work with TLS and a custom SslContext

### ISSUE THREAD

**Issue by sndnv** [akka/akka-grpc#1728]
### Versions used 
sbt-akka-grpc @ 2.1.6

Akka version: 
akka @ 2.6.20

### Expected Behavior
gRPC client with TLS enabled using the netty backend is able to properly connect

### Actual Behavior
An exception is thrown by netty's `GrpcSslContexts.ensureAlpnAndH2Enabled`:
```
ALPN must be enabled and list HTTP/2 as a supported protocol.
```

### Relevant logs
See above

### Reproducible Test Case
Not a public repo so no PR to share

---
As far as I can tell, these issues are related to this piece of code:
```
new JdkSslContext(
      javaSslContext,
      /* boolean isClient */ true,
      /* Iterable<String> ciphers */ null, // use JDK defaults (null is accepted as indicated in constructor Javadoc)
      IdentityCipherSuiteFilter.INSTANCE,
      /* ApplicationProtocolConfig apn */ ApplicationProtocolConfig.DISABLED, // use JDK default (null would also be acceptable, DISABLED config will select the NONE protocol and thus the JdkDefaultApplicationProtocolNegotiator)
      ClientAuth.NONE, // server-only option, which is ignored as isClient=true (as indicated in constructor Javadoc)
      /* String[] protocols */ null, // use JDK defaults (null is accepted as indicated in constructor Javadoc)
      /* boolean startTls */ false)
```
and more specifically, [this](https://github.com/akka/akka-grpc/blob/v2.1.6/runtime/src/main/scala/akka/grpc/internal/NettyClientUtils.scala#L188) line:

```
 /* ApplicationProtocolConfig apn */ ApplicationProtocolConfig.DISABLED, // use JDK default (null would also be acceptable, DISABLED config will select the NONE protocol and thus the JdkDefaultApplicationProtocolNegotiator)
```

If the comment is to be trusted, `JdkDefaultApplicationProtocolNegotiator` will be used and that negotiator provides an empty list of protocols, triggering the above `GrpcSslContexts.ensureAlpnAndH2Enabled` check to fail.

To me it seems that since 2.1.6 there's no way to provide a custom `SslContext` context via `GrpcClientSettings.withSslContext` and have a working client (in other words, breaking change in #1462) or did I miss something?

**Comment by johanandren** [comment]
What JDK version are you using when you see the error?

**Comment by sndnv** [comment]
@johanandren We are building and running on JDK11; I can find out the exact version, if necessary.

**Comment by johanandren** [comment]
If you create a project the akka-grpc-quickstart-scala g8 template, which uses TLS and Netty, does that also not work running the client against the server in the same project? 

I tried with JDK 17, 11 and 8 and client requests work fine for all of those, so it is not generally broken, could there be some additional config you are using complicating things perhaps?

**Comment by sndnv** [comment]
Indeed, we load the TLS certs differently. In the g8 template the cert is provided via config and just loaded. What we do is build an `SslContext` with both trust and key managers so that we can do mutual TLS. We then provide that context to `GrpcClientSettings.withSslContext` (my bad, I should have mentioned that in the description already).

**Comment by johanandren** [comment]
Ok, and the way you set up TLS used to work before 2.1.6?

I wonder if it was this PR/commit breaking it in that case: https://github.com/akka/akka-grpc/commit/b0ff79ecc4382b25bad4e041df6cdbaa3b305343

**Comment by sndnv** [comment]
Indeed, with 2.1.5 it works fine. I'm guessing that's the offending commit.

**Comment by johanandren** [comment]
I took a closer look at this, I don't think we want to revert to the old nasty reflection creation of the Netty SSL context, and I can't figure out if it is possible to pass the right argument without a reproducer. 

Please see if you can create a minimal reproducer, it would only need to be the code setting up the SSL context and creating a client. Alternatively if you can debug your code base and do a PR with logic for the `apn` covering both the default and the mutual TLS case that would be interesting.

**Comment by patriknw** [comment]
This is actually a bug whenever client is setup with custom ssl context.
