### ISSUE TITLE
Send 426 response if protocol isn't supported (HTTP <2)

### ISSUE THREAD

**Issue by richdougherty** [akka/akka-grpc#180]
As mentioned in a related Play PR (https://github.com/playframework/playframework/pull/8357#issuecomment-380259722) we ought to ensure that we have some sort of handling in place for HTTP 1.x requests. My suggestion would be to send a `426 Upgrade Required` response if we receive an HTTP 1.x request.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/426

**Comment by ktoso** [comment]
not entirely sure about this one... todo: clarify

**Comment by johanandren** [comment]
Reading @raboof s comment https://github.com/akka/akka-http/issues/1992#issuecomment-383489312 I don't think there this anything to do here?

**Comment by johanandren** [comment]
Lets' close for now then.
