### ISSUE TITLE
Easier configuration for what to generate

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#190]
Right now we can configure:
* akkaGrpcCodeGenerators (`Seq[GeneratorAndSettings]`, default: ScalaBoth)
* akkaGrpcModelGenerators (`Seq[Target]`, default scalaPB)

Perhaps we should have one `akkaGrpcTargetLanguage` (Java/Scala) to set the default. We could simplify the rest - for the `CodeGenerators` we currently have `Server`, `Client`, and `Both`, so for now that doesn't need to be a `Seq`, but perhaps in the future we'd want to add more specific generators e.g. for Play?

Related to #155

**Comment by 2m** [comment]
> so for now [`CodeGenerators`] doesn't need to be a Seq

We need it as a `Seq` to have java and scala client generated together:

https://github.com/2m/alpakka/blob/bee1644163ca8624000e59cd53dba9569c4e368b/build.sbt#L103-L106

I imagine the settings in the sbt plugin in the end could look lile:

```
akkaGrpcTargetLanguage := Seq(scala), Seq(java) or Seq(scala, java)
akkaGrpcTargetStub := Seq(client), Seq(server) or Seq(client, server)
```

**Comment by johanandren** [comment]
I like martynas suggestion, I'll try to do that.
