### ISSUE TITLE
Different settings for Compile/Test with sbt

### ISSUE THREAD

**Issue by johanandren** [akka/akka-grpc#194]
The current somewhat complicated sbt settings are motivated by the idea that it would be possible to generate only a server in `Compile` and then the client in `Test` to do integration tests in the same project. However, there is no test coverage for this and when I tried to create a scripted test it seems it does in fact not work.

I think we should either make sure it works, has a test covering it and is described in the sbt plugin docs or simplify the plugin settings and simply not support it.

**Comment by viktorklang** [comment]
I managed to get this to work without any code changes,

This is what I added to be able to do it:

```scala
    inConfig(Test)(
      sbtprotoc.ProtocPlugin.protobufConfigSettings ++ Seq(
        PB.protoSources ++= Seq(sourceDirectory.value / "protos"),
        akkaGrpcGeneratedSources := Seq(AkkaGrpc.Client),
      )
    ),
```

This configures the ProtocPlugin to work under Test, and then adds test/protos as the proto sources to compile, and the akkaGrpcGeneratedSources will then only generate the client.

**Comment by raboof** [comment]
Together with #702 I think we can now consider this issue closed
