### ISSUE TITLE
Test and document proxy support

### ISSUE THREAD

**Issue by patriknw** [akka/akka-grpc#206]
Especially Envoy Proxy and OpenShift HAProxy are important

**Comment by patriknw** [comment]
PM decided that the scope of this for MVP is Envoy only

**Comment by johanandren** [comment]
Things to try:

* TLS all the way through
* Proxy terminating TLS and then plaintext HTTP2
* Load balancing
* Killing the server while there is an ongoing proxied connection

**Comment by johanandren** [comment]
First result: 
gRPC over unencrypted HTTP2 works through Envoy, unary, bidirectional and client streaming works but server streaming has request killed as soon as the first element has been sent to client, I think because of this issue: https://github.com/envoyproxy/envoy/issues/3724
