### ISSUE TITLE
Provide a gRPC server in a Play application

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#209]
Documentation, example project (perhaps based on https://github.com/raboof/play-scala-grpc-server), and utilities to make this smooth.

Requires https://github.com/akka/akka-http/issues/1966 and perhaps #150 

Design decisions: 
* Where do these utilities live? Putting them in the akka-grpc project seems convenient as long as we're still moving quickly, but once our API's stabilize we might want to move them to a Play gRPC subproject since generation might be different for different Play versions.
* Should the akka-grpc handlers be added 'automatically' (DI'ing the service implementations?) or should users add them to their routes definition file? Adding them to the routes definition file seems most 'native'.
* the generated handler will expect the server implementation to be injected. This can be done by type or by name. When injecting by type, this must be the `FooServiceImpl` type, since the `FooService` interface is also used by the client so will be ambiguous. Alternatively, we could avoid referring to `FooServiceImpl` in the router, but inject the correct `FooService` instance by name. This however would mean we would have to generate bindings from the `FooServiceImpl` to the name, which again introduces the need to refer to the implementation class name, so that does not buy us much. Expecting the implementation under `controllers` seems fine for now.

Progress:
* [x] Scala codegen (#251)
* [x] Java codegen (#274)
* [ ] Scala example project (perhaps based on https://github.com/raboof/play-scala-grpc-server)
* [ ] Java example project
* [x] Documentation

**Comment by johanandren** [comment]
Working on the h2c support

**Comment by raboof** [comment]
h2c `Upgrade` support progress is in https://github.com/akka/akka-http/pull/2075. Looks good with curl, nghttp and wireshark AFAICS, but the grpc-java client crashes on our (AFAICS correct) response to the original request request coming in as stream 1.

For Play we have a couple of options to have 'normal' and gRPC routes co-exist:
- Use `h2c` with `Upgrade`
- Introduce a third port next to `http` and `https`, serving the routes over `h2c` without `Upgrade`
- Introduce a flag to switch the `http` port to `h2c` without `Upgrade`
- Only support HTTP2 on the https port

- `h2c`+`Upgrade` seems nicest, but perhaps not possibe for the MVP as it seems it'd require switching to Akka HTTP at the client
- Introducing a third port might be tricky in Play, as it uses a 'port pair' in a lot of the code - though we may still want this in the future.
- Switching the `http` port to `h2c` makes it unusable from browsers, which seems like a showstopper
- Doing gRPC only on the HTTPS port (with a ALPN and a self-signed certificate for development) might OK for MVP

**Comment by ktoso** [comment]
Scala and Java side done then

**Comment by johanandren** [comment]
@richdougherty this is the idea for the server side

**Comment by johanandren** [comment]
Created separate tickets to track the in-play docs and the example projects.
