### ISSUE TITLE
Don't require `/certs/` folder

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-grpc#231]
`GrpcClientSettings#certificate` is the file name of a CA cert to trust. 

We shouldn't require the trusted CA cert to be placed in `/certs/`.

Related to https://github.com/akka/akka-grpc/pull/230

**Comment by ignasi35** [comment]
Actually, fix the [`FIXME`](https://github.com/akka/akka-grpc/blob/c21034fab090a20ca27d595134f33d8221f11e8b/runtime/src/main/scala/akka/grpc/GrpcClientSettings.scala#L12)

**Comment by raboof** [comment]
Also related to #89

**Comment by raboof** [comment]
This was fixed as part of #266
