### ISSUE TITLE
Prefer Major.Minor.patch version names

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-grpc#236]
The current release of `akka-grpc` is `"0.1"` which is not `Major.Minor.patch`. 

The build/release process uses `sbt-git` so the release name depends on the tag the admin running the release decides. I don't know if we could include an enforcer that's used during the release to check the tag format.

**Comment by patriknw** [comment]
we typically start "real" versioning after 1.0.0, before that it's wild with possible breaking changes in each release and therefore no patches

**Comment by ignasi35** [comment]
thanks for clarifying. :-)
