### ISSUE TITLE
Don't dictate 'controller' package for implementation

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#279]
After discussing with the Play and Lagom projects, it seems the top-level 'controller' package is not a very widely used convention anymore. 

We should either find a way to avoid dictating a package at all (perhaps we can find a way injecting the interface after all) or default to the package from the proto file.

**Comment by raboof** [comment]
Experimented in https://github.com/raboof/play-scala-grpc-server/pull/7 but no luck just yet

**Comment by johanandren** [comment]
Solved by #291
