### ISSUE TITLE
ServiceDiscovery method in GrpcClientSettings 

### ISSUE THREAD

**Issue by patriknw** [akka/akka-grpc#281]
`def apply(config: Config)` should load ServiceDiscovery instance from configured method.
See https://github.com/akka/akka-management/pull/230

After https://github.com/akka/akka-grpc/pull/260

**Comment by chbatey** [comment]
Depends on 0.16 release of akka-management

**Comment by chbatey** [comment]
We need an ActorSystem to be able to use ServiceDiscovery so i've added it to the `apply(config: Config)` we can add back in a version without but that means we'd have a config param for service discovery but have to ignore it in that case
