### ISSUE TITLE
Use gRPC in Lagom online auction example

### ISSUE THREAD

**Issue by patriknw** [akka/akka-grpc#283]
Convert the existing online auction example to learn the differences between gRPC and Lagom service calls. May not end as a published example but outcome might be some documentation.

Start by just replacing one service-to-service call.

**Comment by johanandren** [comment]
This depends on the work that @renatocaval has started (and which we had a meeting about today) which provides a play router and a way to hook that together with a path prefix (which is used for automagic proxying) into the lagom server.

**Comment by ktoso** [comment]
The mentioned Renato's work is https://github.com/lagom/lagom/pull/1440
Though I suppose we could start on this soon or even already

**Comment by raboof** [comment]
Lagom TLS is WiP at https://github.com/lagom/lagom/pull/1443

**Comment by ktoso** [comment]
Ok got it, so pending for now

**Comment by dwijnand** [comment]
Moving back to TODO and un-assigning Konrad.

**Comment by ignasi35** [comment]
Online-auction has been archived.
