### ISSUE TITLE
Opposite streams block each other

### ISSUE THREAD

**Issue by peteremiljensen** [akka/akka-grpc#285]
I don't know if the following is a bug or what.

I have a situation where a long-lived stream is used to stream calculated data from client to server.
With the same client I have a second stream, which is used to retrieve data from the server.

The problems arises when the first stream is open and is not sending anything, it blocks the second stream from retrieving data.

Sincerely,
Peter

**Comment by johanandren** [comment]
Do you have a reproducer you can share?

**Comment by peteremiljensen** [comment]
Hey. I will try to find time to reproduce an example

**Comment by peteremiljensen** [comment]
I've created reproducer in the following forked repo:
https://github.com/peteremiljensen/akka-grpc 
It's called `OppositeTest.scala` in `plugin-tester-scala` 

The reproducer works by firsting starting a client stream, which is streaming nothing, and killed after 30 seconds. The server stream is created immediately after the client stream, but is not streaming anything until the client stream is killed. 
But the issue is not occurring every time. However, it seems to occur oftener the more concurrent client streams I have.

I hope it helps

**Comment by johanandren** [comment]
Thanks! I'll take a look.

**Comment by johanandren** [comment]
Here's a somewhat more minimal reproducer, confirming that there is an issue:

```
object Reproducer extends App {

  /*
  service OppositeService {
    rpc serverStreaming (ClientMessage) returns (stream ServerMessage) {}
    rpc clientStreaming (stream ClientMessage) returns (ServerMessage) {}
  }

  message ServerMessage {
      string payload = 1;
  }
  
  message ClientMessage {
      string payload = 1;
  }
  
   */
  
  
  class OppositeServiceImpl(implicit mat: Materializer, sys: ActorSystem, ec: ExecutionContext) extends OppositeService {

    def serverStreaming(in: ClientMessage): Source[ServerMessage, NotUsed] =
      Source(0 to 10000)
        .map { x =>
          sys.log.info(s"Server: streaming $x to client")
          ServerMessage(x.toString)
        }

    def clientStreaming(in: Source[ClientMessage, NotUsed]): Future[ServerMessage] =
      in.runWith(Sink.ignore)
        .map(_ => ServerMessage("Server: client streaming done"))
  }

  val conf = ConfigFactory.parseString("akka.http.server.preview.enable-http2 = on")
    .withFallback(ConfigFactory.defaultApplication())
  implicit val sys: ActorSystem = ActorSystem("client", conf)
  implicit val mat: Materializer = ActorMaterializer()
  implicit val ec: ExecutionContext = sys.dispatcher

  val oppositeService =
    OppositeServiceHandler(new OppositeServiceImpl)

  val binding = Await.result(Http().bindAndHandleAsync(
    oppositeService,
    interface = "127.0.0.1",
    port = 8081,
    connectionContext = HttpConnectionContext(UseHttp2.Always)
  ), 10.seconds)
  val client = new OppositeServiceClient(GrpcClientSettings("127.0.0.1", 8081))

  sys.log.info("Client: Starting server stream")
  client
    .serverStreaming(ClientMessage(""))
    .runForeach(elem => sys.log.info(s"Client: from server: $elem"))

  sys.log.info(s"Starting client streams not emitting for 30 seconds")
  client.clientStreaming(Source.maybe[ClientMessage]
    .takeWithin(30.seconds)
    .mapMaterializedValue(_ => NotUsed))
}
```

Gives the output:
```
[INFO] [07/16/2018 18:09:18.348] [main] [akka.actor.ActorSystemImpl(client)] Client: Starting server stream
[INFO] [07/16/2018 18:09:18.358] [main] [akka.actor.ActorSystemImpl(client)] Starting client streams not emitting for 30 seconds
[INFO] [07/16/2018 18:09:48.494] [client-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(client)] Server: client streaming done
[INFO] [07/16/2018 18:09:48.545] [client-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(client)] Server: streaming 0 to client
[INFO] [07/16/2018 18:09:48.547] [client-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(client)] Client: from server: ServerMessage(0)
```

Haven't dug into why yet, could it be that we are sharing the internal Netty client though it can only handle one request at a time (and who get's to do that request first is racy)?

**Comment by johanandren** [comment]
Here are some logs with Netty debug output enabled:
[weirdness.log](https://github.com/akka/akka-grpc/files/2201291/weirdness.log)

**Comment by johanandren** [comment]
Netty client + Akka HTTP/2 server debug logs: 
[weirdness.log](https://github.com/akka/akka-grpc/files/2201552/weirdness.log)

**Comment by peteremiljensen** [comment]
Hey. I'm unfortunately hold back by this bug. Do you have any expected fix in nearby future?

Thanks

**Comment by jrudolph** [comment]
It seems the problem is that `bindAndHandleAsync` is called with default `parallelism = 1` which means that only one request is handled at a time on the server side.

This setting defaults to `1` because in HTTP/1 we assume that pipelining is switched off so handling one request at a time *per connection* seems enough.

For HTTP/2, however, it doesn't really make sense as we want to allow multiplexing multiple requests per connection. It's somewhat weird that this never came up in the context of HTTP/2 itself. I guess the reason is that during HTTP/2 testing we never tested running multiple `HttpRequest => Future[HttpResponse]` at the same time but only tested streaming out the response.

So, in this case not completing the future returned from `clientStreaming`, means that later requests are blocked behind that one.

I created https://github.com/akka/akka-http/issues/2145 to at least improve documentation in akka-http.

**Comment by patriknw** [comment]
Great that there was a simple explanation.

**Comment by peteremiljensen** [comment]
Fantastic 👍
