### ISSUE TITLE
Make proto/srcDir configurable for Gradle

### ISSUE THREAD

**Issue by patriknw** [akka/akka-grpc#288]
Using `src/main/protobuf` now without config option.

**Comment by raboof** [comment]
:+1: (perhaps looking at https://github.com/google/protobuf-gradle-plugin#configuring-protobuf-compilation for inspiration)

**Comment by chbatey** [comment]
It uses proto for Java and protobuf for Scala atm

**Comment by eshepelyuk** [comment]
I think this issue should be closed, since `proto` dir is configured by external `protobuf` plugin and not this one.

```
sourceSets {
  main {
     proto {
       srcDir "my-source-folder'
    }
  }
}
```

**Comment by raboof** [comment]
Seems OK to leave that up to the upstream plugin
