### ISSUE TITLE
Empty.java in Gradle Scala project

### ISSUE THREAD

**Issue by patriknw** [akka/akka-grpc#289]
For unknown reason the Gradle complains about no java sources. The workaround was to add an `Empty.java` file in src/main/java, but would be nice to make it work without that.

Should also be fixed in Quickstarts

**Comment by style95** [comment]
Any updates on this issue?
I want to remove annoying `Empty.java` file from my project.

**Comment by raboof** [comment]
No - I'm not very familiar with Gradle so I'd be very interested if someone can shed light on this!

**Comment by eshepelyuk** [comment]
This is side-effect of protobuf plugin. Probably could be hacked. Will try to figure out.

**Comment by raboof** [comment]
Thanks again!
