### ISSUE TITLE
group/tab not rendered if inline snippet contains empty line

### ISSUE THREAD

**Issue by patriknw** [akka/akka-grpc#294]
Shadow ticket of https://github.com/lightbend/paradox/issues/224

Probably best to fix the parsing in Paradox, and then we could add some empty lines to the embedded snippets again. E.g. the gradle scripts would look better with some space.

I tried to combine ```@@@vars`` (to replace the `$projectversion$` with `@@snip` but didn't get that to work.

**Comment by ennru** [comment]
This is a problem in Paradox https://github.com/lightbend/paradox/issues/161.
