### ISSUE TITLE
Add Akka gRPC Play docs in the Play documentation

### ISSUE THREAD

**Issue by johanandren** [akka/akka-grpc#300]
Split out from #209 and #208 as I think this is hard before having an up to date Akka gRPC artifact published.

I think we could easily just port the docs that are now in the Akka gRPC docs to the Play framework docs system.

**Comment by johanandren** [comment]
In a call with the play team it turned out the play docs could also pull in an artifact with docs and add to the play docs, so it could also live with this project. Not sure what is best.

**Comment by TimMoore** [comment]
Maybe it would make sense for unified gRPC documentation (for Akka, Play and Lagom) to be on developer.lightbend.com?

**Comment by raboof** [comment]
The Akka gRPC docs are already at https://developer.lightbend.com/docs/akka-grpc/current/, but previously we figured it would feel more coherent/native to move the Play section to the Play documentation - adding links between that section and the "raw" Akka gRPC docs.
