### ISSUE TITLE
Play Framework example projects 

### ISSUE THREAD

**Issue by johanandren** [akka/akka-grpc#301]
Split out from #208 and #209 for easier tracking

**Comment by johanandren** [comment]
Never really got anywhere with this, so feel free to pick it up. Would be good if @richdougherty or @marcospereira did one of the samples to see if the current integration "fits" with Play in the right way.

**Comment by ktoso** [comment]
I'm on it

**Comment by ktoso** [comment]
Closing for now, the Gradle things remain though -- shall I new ticket for it?

**Comment by ktoso** [comment]
Ticket is: https://github.com/akka/akka-grpc/issues/342
