### ISSUE TITLE
Make protobuf directories consistent

### ISSUE THREAD

**Issue by chbatey** [akka/akka-grpc#323]
Ideally all build tools could pick up from proto (standard for java tooling) and protobuf (scalapb). If not make build tools consistent so SBT protobuf regardless of language and Gradle/Maven proto regardless of language and override defaults in sample projects so they work with all 3 build tools

**Comment by jrudolph** [comment]
Is this now closed? And what was the final decision which directories to show by default? If we chose to use `proto` everywhere we might want to adapt it in the Scala documentation.

**Comment by ktoso** [comment]
Suggestion was to:

- support both - done
- show docs consistent with what given build tool likes - not sure if done, please confirm @chbatey @raboof ?

**Comment by chbatey** [comment]
We should do a check of the docs then close this.

**Comment by raboof** [comment]
checking
