### ISSUE TITLE
Documentation: clarify more when and why to use gRPC

### ISSUE THREAD

**Issue by ktoso** [akka/akka-grpc#326]
Feedback from @TimMoore 

> Documentation, both for the core project and how to use with Play/Lagom. Also: not only how to use, but why. (I have to admit, I only just found https://developer.lightbend.com/docs/akka-grpc/snapshot/index.html, so I haven't read it all yet.)

**Comment by jrudolph** [comment]
I added slightly more info to a new page here: https://github.com/akka/akka-grpc/pull/339/files#diff-5d45f8af2b92b94373d47c7a8e01d8b0

**Comment by ennru** [comment]
Covered with https://doc.akka.io/docs/akka-grpc/current/whygrpc.html
