### ISSUE TITLE
Play+Gradle support

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#342]
Unfortunately, since we require Play 2.7+ and Gradle does not yet support Play 2.7+ (https://github.com/gradle/gradle/issues/6362), this combination does not currently work end-to-end.

**Comment by ennru** [comment]
This is supported with Play 2.8.x.
See https://developer.lightbend.com/docs/play-grpc/current/play/gradle-support.html

**Comment by raboof** [comment]
(also this issue would belong in https://github.com/playframework/play-grpc/ nowadays ;) )
