### ISSUE TITLE
Cross-build for Scala 2.11

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#345]

**Comment by ktoso** [comment]
Sanity check, happening for 0.2? Would be nice if not troublesome

**Comment by chbatey** [comment]
Not planned to but we can

**Comment by 2m** [comment]
We would like a release of akka-grpc for Scala 2.11 for the https://github.com/akka/alpakka/pull/1162

If you want I can try to cut it. :)

**Comment by patriknw** [comment]
That would be great @2m, I don't think we have a reason for not doing it.

**Comment by 2m** [comment]
Can we cut a release of `0.4`? I think it should only be a matter of creating a release in GitHub.
