### ISSUE TITLE
Create publishable Play test artifact

### ISSUE THREAD

**Issue by richdougherty** [akka/akka-grpc#359]
Create an artifact that contains gRPC test helpers for Play that can be used with ScalaTest, specs2 and JUnit. The artifact will be used internally by the play-interop projects contained in the akka-grpc repo. It will also be used by our Play gRPC example projects. Users who want to test our pre-release versions of akka-grpc can use the artifact too.

In the future this artifact will be split into code that will live in the play-test, play-java, play-specs2 and scalatestplus-play artifacts. For now, we'll keep the code in a single artifact inside the akka-grpc repo so that it's faster for us to work with and improve. Since this artifact bundles together several different types of test frameworks, these dependencies should be marked as "provided" so that they don't automatically get pulled in when the artifact is used. 

By request of the Akka team the artifact should contain the name "testkit". For example, it could be called something like "akka-grpc-play-testkit".

Depends on #356, which creates gRPC test helpers for ScalaTest and specs2.

We need to create this artifact before we can do several other things like add tests to our example code and add Java test helpers.

**Comment by richdougherty** [comment]
Still waiting on #356. Until then I've prototyped the work here: https://github.com/akka/akka-grpc/compare/master...richdougherty:play-testkit

**Comment by raboof** [comment]
Unfortunately we really want akka-http 10.1.4 because it contains the fix for https://github.com/akka/akka-http/issues/2110.. perhaps we should consider cutting 10.1.5 relatively soon.

**Comment by richdougherty** [comment]
I decided to move this into #356 anyway, since that PR was still not merged, and since I needed to rewrite how dependencies worked to get it compiling.
