### ISSUE TITLE
Tech Hub Example Issue

### ISSUE THREAD

**Issue by hungaikev** [akka/akka-grpc#376]
I am trying out the akka-grpc example but I am not able to download the `akka-grpc-quick-start` template from Techhub. (https://developer.lightbend.com/start/?group=akka&project=akka-grpc-quickstart-scala) Below is the error I am getting. 

<img width="837" alt="screen shot 2018-08-27 at 18 18 30" src="https://user-images.githubusercontent.com/1276871/44668312-b7440400-aa25-11e8-90e5-09f2c3141e0e.png">

The same error occurs while trying to download the java one too.

**Comment by raboof** [comment]
This is still failing for me - could be just a matter of deploying though?

**Comment by hungaikev** [comment]
Still fails for me too. I closed it after realizing the duplicate issue https://github.com/lightbend/techhub/issues/211. Can we keep it open until it is solved?

**Comment by raboof** [comment]
(now successfully deployed)

**Comment by hungaikev** [comment]
Thanks @raboof It works on my end too.
