### ISSUE TITLE
Bazel build tool support

### ISSUE THREAD

**Issue by offerijns** [akka/akka-grpc#408]
I was wondering if there are any plans to support other build tools; in particular, do you plan to add support for Bazel? At the moment, there's support for ScalaPB through the `scalapb_proto_library` rule in this package: https://github.com/bazelbuild/rules_scala. However, I would love to use this library instead of ScalaPB.

There is already an undocumented argument in this rule for passing a custom generator: https://github.com/bazelbuild/rules_scala/blob/7d88e0e1fa415e79fd80443279896357937ce5ba/scala_proto/scala_proto.bzl#L410. I have been trying to figure out how to plug `akka-grpc` here, but I don't have enough understanding of the way it works (yet) to figure this out.

**Comment by patriknw** [comment]
There are no plans to support more than the 3. It has been difficult enough to get it working with those, and maintaining more is beyond what we can take care of. If you want to build your own integration and find anything that could make it easer we can of course discuss that.

OK to close?

**Comment by ktoso** [comment]
As much as bazel is a very cool build tool, I agree with Patrik that the team is not able to take on maintanance of such integration.

If you want to give it a shot, perhaps the best place would be a separate repository to prototype it.
Feel free to ask questions on https://discuss.akka.io if you needed some help with regards to how to integrate with akka-grpc.

Closing for now though, to not give the impression this will be worked on actively by the team

**Comment by offerijns** [comment]
Makes sense! Thanks for the quick reply.

I'll definitely see if I can set up the integration myself.

**Comment by jsbrucker** [comment]
@offerijns did you end up setting up your own bazel integration?

**Comment by BillyAutrey** [comment]
@patriknw Is [akka.grpc.gen.Main](https://github.com/akka/akka-grpc/blob/main/codegen/src/main/scala/akka/grpc/gen/Main.scala) usable as a general purpose entry point to generate the Akka gRPC generated client/server?

**Comment by raboof** [comment]
> The code indicates that it is used by the Gradle plugin. However, if it is really just general purpose, it seems like it might be usable in Bazel to generate these files.

Yes, that might definitely be! Also for maven, you can use the `akka-grpc-scalapb-protoc-plugin_2.12` artifact as a protoc plugin 'directly' instead of using the akka-grpc plugin - see for example https://github.com/lightbend/akkaserverless-java-sdk/blob/main/samples/java-eventsourced-customer-registry/pom.xml#L75-L83 . I'm not *sure* this would work from Bazel but it's definitely worth investigating.

**Comment by BillyAutrey** [comment]
> Yes, that might definitely be! Also for maven, you can use the `akka-grpc-scalapb-protoc-plugin_2.12` artifact as a protoc plugin 'directly' instead of using the akka-grpc plugin if you need more control - see for example https://github.com/lightbend/akkaserverless-java-sdk/blob/main/samples/java-eventsourced-customer-registry/pom.xml#L75-L83 . I'm not _sure_ this would work from Bazel but it's definitely worth investigating.

Cool, I'll give it a shot and report back.  Thanks @raboof!

**Comment by BillyAutrey** [comment]
Well, substituting the main out in `code_generator` did not work as expected.  Seems like that's a very bazel-specific worker substitution, which is not really what we want.

A path that seems to be working better is to substitute `extra_generator_dependencies` and `named_generators`, and all of the generators will run.  However, for this to work, the class that has to be provided needs to extend `protocbridge.ProtocCodeGenerator`.

The good news is, it seems like it shouldn't be *too* hard to do this.  The inputs/outputs look comparable.  Just needs to be written.

**Comment by raboof** [comment]
> A path that seems to be working better is to substitute `extra_generator_dependencies` and `named_generators`, and all of the generators will run. However, for this to work, the class that has to be provided needs to extend `protocbridge.ProtocCodeGenerator`.
> 
> The good news is, it seems like it shouldn't be _too_ hard to do this. The inputs/outputs look comparable. Just needs to be written.

Aha, I think we do something similar in the SBT plugin, https://github.com/akka/akka-grpc/blob/main/sbt-plugin/src/main/scala/akka/grpc/sbt/GeneratorBridge.scala

**Comment by BillyAutrey** [comment]
Cool!  I'm just hammering around a little bit, so this can be improved.  But, I was able to call all of the generators successfully from Bazel!  Just had to do something like this:

```
class TraitBuilder extends ProtocCodeGenerator {
  override def run(request: Array[Byte]): Array[Byte] = {
    ScalaTraitCodeGenerator.run(request,StdoutLogger)
  }
}

class ClientBuilder extends ProtocCodeGenerator {
  override def run(request: Array[Byte]): Array[Byte] = {
    ScalaClientCodeGenerator.run(request,StdoutLogger)
  }
}

class ServerBuilder extends ProtocCodeGenerator {
  override def run(request: Array[Byte]): Array[Byte] = {
    ScalaServerCodeGenerator.run(request,StdoutLogger)
  }
}
```
And then, I could add each of them as a `named_generator` in my `scala_proto_toolchain`.  Only problem I have now is, I need to figure out how to configure which of the generators is called per Bazel target.

Thanks for the help @raboof!
