### ISSUE TITLE
Code generators should be enabled by scope

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-grpc#410]
When writing a gRPC server, a server code generator is required.

Writing tests for such server requires a client but the generated client should not be live in  `/src_generated/main` but `/src_generated/test`.

E.g.: instead of having to do 

```scala
  .settings(
    akkaGrpcGeneratedLanguages := Seq(AkkaGrpc.Scala),
    akkaGrpcGeneratedSources := Seq(AkkaGrpc.Server, AkkaGrpc.Client)
  ).settings(

```
something like the following should be supported:
```scala
  .settings(
    akkaGrpcGeneratedLanguages := Seq(AkkaGrpc.Scala),
    akkaGrpcGeneratedSources in Compile := Seq(AkkaGrpc.Server),
    akkaGrpcGeneratedSources in Test := Seq(AkkaGrpc.Client)
  ).settings(

```

**Comment by ignasi35** [comment]
This may be already supported and it's just my `sbt` noob-ness kicking in. 😅

**Comment by raboof** [comment]
This would be interesting and I'm quite sure we don't support this right now.

**Comment by ignasi35** [comment]
duplicate indeed. Closing this in favour of #194
