### ISSUE TITLE
Clarify client-side ALPN requirement in play documentation

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#412]
In the Play documentation, it is not clear that for the client side, you need to either load the ALPN agent, or disable TLS.

**Comment by indusbull** [comment]
@raboof  Till documents are updated, can you guys pls provide clarity here what one supposed to do.

I am running into issue as described [here](https://discuss.lightbend.com/t/akka-grpc-running-client-only-from-play-http2/2286/3)

**Comment by raboof** [comment]
Hmm that might very well be true. If that changes when we switch to an Akka HTTP-based client we'll cross that bridge.
