### ISSUE TITLE
Integrate with Gradle for Scala projects

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#42]
Related to #6 

For Scala we could choose to invoke scalapb as a protoc plugin, or use https://github.com/CharlesAHunt/scalapb-gradle-plugin

**Comment by 2m** [comment]
Fixed in https://github.com/akka/akka-grpc/pull/154

**Comment by gortiz** [comment]
Are there plans to upload the gradle plugin to Maven Central or somewhere else?

**Comment by raboof** [comment]
Hi @gortiz - yes, ideally I think we would upload the plugin to the Gradle plugin portal (https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal), though right now we do not have this in place just yet.
