### ISSUE TITLE
Set Content-Type response header

### ISSUE THREAD

**Issue by ctoomey** [akka/akka-grpc#428]
Per the grpc wire format [spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)., the response must include a `Content-Type` header, and currently it doesn't.

**Comment by ctoomey** [comment]
I tried adding the header [here](https://github.com/akka/akka-grpc/blob/e8278352d32258248cb6e83cfa9faaf543b4b82d/runtime/src/main/scala/akka/grpc/internal/GrpcResponseHelpers.scala#L55) but it was rejected by akka-http [here](https://github.com/akka/akka-http/blob/master/akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala#L120).

When I did a local build of akka-http to disable that check, the header was successfully delivered and the [android test client](https://grpc.io/docs/quickstart/android.html) that didn't work without it worked.

I'll file a separate ticket against akka-http on this.

**Comment by raboof** [comment]
As mentioned in https://github.com/akka/akka-http/issues/2245 the `Content-Type` header is set from the `HttpEntity`. We set this value at https://github.com/akka/akka-grpc/blob/master/runtime/src/main/scala/akka/grpc/internal/GrpcResponseHelpers.scala#L56, to the specific `application/grpc+proto` content-type defined as a constant at https://github.com/akka/akka-grpc/blob/master/runtime/src/main/scala/akka/grpc/Grpc.scala#L19.

We'd have to look into why the android test client apparently doesn't accept this - does it require specifically `application/grpc` and not recognize `application/grpc+proto`?

**Comment by ctoomey** [comment]
Sorry, turned out to be a bug in my implementation of server power API using Play actions (#429) where I wasn't properly copying the HttpEntity content type.
