### ISSUE TITLE
Include .proto comments in generated gRPC stubs

### ISSUE THREAD

**Issue by ctoomey** [akka/akka-grpc#432]
The generated service trait and server stubs in Scala don't currently include the attached comments from the .proto files. I haven't checked the generated Java server or Java/Scala client code but expect it's not included in them either. The attached comments _are_ included for the generated message code.

It'd be really helpful to include this documentation in the generated code so it's available when implementing. I haven't tried it but it [looks like](https://github.com/grpc/grpc-java/issues/1612) grpc-java does this.

**Comment by bjaglin** [comment]
I have opened https://github.com/scalapb/ScalaPB/pull/534 to add comments in the `ScalaPB`-generated stubs, so when/if this is merged, it should be possible to use the pimp `comment` methods.

**Comment by bjaglin** [comment]
The path to bumping ScalaPB will be blocked by https://github.com/akka/akka-grpc/pull/473, so I am trying to unlock it in https://github.com/akka/akka-grpc/pull/500.

**Comment by raboof** [comment]
(#500 is now merged)

**Comment by bjaglin** [comment]
thanks @raboof - I have a PR in good shape for this, just waiting for a ScalaPB release that includes https://github.com/scalapb/ScalaPB/pull/534
