### ISSUE TITLE
custom protobuf source directory - ignore default protobuf directory

### ISSUE THREAD

**Issue by indusbull** [akka/akka-grpc#443]
In my project, I already have existing non-grpc protobuf files which are  in "src/main/protobuf/existing" directory.  Now when I enable akka-grpc plugin, I want to generate code only grpc protofbuf files in "src/main/protobuf/grpc" directory. 

Based on [docs](https://developer.lightbend.com/docs/akka-grpc/current/buildtools/sbt.html#proto-source-directory), I can add my custom protobuf directory in build.sbt as follow -

```
// "sourceDirectory in Compile" is "src/main", so this adds "src/main/proto_custom":
inConfig(Compile)(Seq(
  PB.protoSources += sourceDirectory.value / "protobuf/grpc"
))
```
I was expecting plugin in to look for protobuf files only in  src/main/protobuf/grpc directory. But it also tries to generate code for proto files in "src/main/protobuf/existing"  as well.

I also tried moving grpc protofiles to "src/main/grpc_protobuf" but it still picks up protofiles from "src/main/protobuf/existing". 

Is there any config to exclude default protobuf directory?

**Comment by dwijnand** [comment]
Is this specific to akka-grpc's sbt plugin, or is it separately reproducible on the grpc sbt plugin?

**Comment by indusbull** [comment]
We have tried only akka-grpc sbt plugin. Can you point me towards which other grpc sbt plugin you are referring to?

**Comment by dwijnand** [comment]
Sure: https://github.com/scalapb/ScalaPB

**Comment by raboof** [comment]
I haven't double-checked, but I'd expect you could use `PB.protoSources := Seq(sourceDirectory.value / "protobuf/grpc")` to replace the value for this part of the configuration rather than adding to it. Does that work for you?

**Comment by indusbull** [comment]
@raboof 
Forgot to update here that @raboof suggestion works!

**Comment by TimMoore** [comment]
Thanks for confirming, @indusbull!
