### ISSUE TITLE
Add a way to replace GrpcExceptionHandler with a custom implementation

### ISSUE THREAD

**Issue by KonstantinTsykulenko** [akka/akka-grpc#448]
Currently GrpcExceptionHandler seems to be baked into the generated server code with no neat way to replace it. It would be nice to be able to provide a custom exception handler.

**Comment by raboof** [comment]
Agreed! Would you be interested in looking into contributing this?

**Comment by KonstantinTsykulenko** [comment]
Yep, I'll take a look and see what I can do.

**Comment by ctoomey** [comment]
We'd like to have this too. @KonstantinTsykulenko  have you made any progress on this or do you expect to any time soon?

**Comment by ctoomey** [comment]
Note than in addition to being able to customize exception handling for unary-response APIs, which `GrpcExceptionHandler` is used for, a separate means to customize exception handling for streaming-response APIs is desirable. This is currently hardcoded at https://github.com/akka/akka-grpc/blob/master/runtime/src/main/scala/akka/grpc/internal/GrpcResponseHelpers.scala#L39 .

**Comment by raboof** [comment]
I agree the exception handling for failed streams should also go through the (to-be-configurable) exception handler

**Comment by ctoomey** [comment]
See https://github.com/akka/akka-grpc/pull/502

**Comment by raboof** [comment]
Thanks @ctoomey for the contribution! @KonstantinTsykulenko could you have a look whether this is sufficient for your use case as well?

**Comment by ctoomey** [comment]
@raboof happy to be able to contribute back what we need ourselves Thanks for merging.

**Comment by wb14123** [comment]
Hi @ctoomey , is there any example about how to use a custom exception handler?

**Comment by ctoomey** [comment]
@wb14123 I don't have a single code example handy, but an additional constructor taking a custom exception handler argument was added to the templates for the generated [Handler](https://github.com/akka/akka-grpc/pull/502/files#diff-89817a0a1f4a6377f320c5d7247026a84eeb520f85d772482e76520c1eb98a88) and [Router](https://github.com/akka/akka-grpc/pull/502/files#diff-747d8305ecef8da90c026953857ffd0200712ffce5989279b97becee9f7360fe). An example of such a custom exception handler is given in the [test](https://github.com/akka/akka-grpc/pull/502/files#diff-6e2b4d256de85e6481b31837bbc2cb086c0ebc12dc2b65557bb01c5bb1a0d0ad).
