### ISSUE TITLE
support .proto files without package declarations

### ISSUE THREAD

**Issue by lucasvfventura** [akka/akka-grpc#450]
I don't even know if this is possible, but I follow the quick-start-scala and used the same proto file to generate a Node.js client and it didn't work. Getting the error:  Received http2 header with status: 404

I was able to do this using pure ScalaPB and Node.js.

Any thoughts?

**Comment by raboof** [comment]
That is definitely intended to work - and indeed we've successfully tested an akka-grpc based server with the external https://github.com/njpatel/grpcc command-line tool that can dynamically generate clients based on protobuf definitions. Can you try with grpcc? Does the Node.js client also support insecure ('prior knowledge') connections? If so, perhaps inspecting the exchange in Wireshark might shine some light on what might be going wrong?

**Comment by lucasvfventura** [comment]
Thank you for the reply. Yes Node does support insecure.
I tried the grpcc and got the same error:
 code: 1,
  metadata:
   { ':status': '404',
     'content-length': '0',
     date: 'Thu, 01 Nov 2018 22:50:14 GMT',
     server: 'akka-http/10.1.5' },
  details: 'Received http2 header with status: 404' }

**Comment by lucasvfventura** [comment]
Just to let everyone know I fix the issue by simple adding the package declaration proto file:
package helloworld;

**Comment by raboof** [comment]
Great to hear! Maybe let's keep this issue open to see if we can produce a useful diagnostic message in this case, since this does look pretty puzzling.

**Comment by raboof** [comment]
I just received a report of a situation where the server (in another technology) worked fine with `grpcurl` but not with the akka-grpc client, which was also fixed by adding a package declaration to the proto file.

Looks like we should really look into what should happen when there is no package declaration present.

**Comment by chbatey** [comment]
I had a look at this in wireshark. We generate method descriptors with the incorrect name if a package isn't set. Fixed in #650 and tested with grpc-java
