### ISSUE TITLE
Make ALPN for HTTP/2 over TLS work with java11

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#468]
This likely requires fixing this in upstream akka-http as described in https://github.com/akka/akka-http/issues/2280

**Comment by ctoomey** [comment]
Will the next release of akka-grpc require akka-http 10.1.8 then? Any idea on ETA of that next release?

**Comment by raboof** [comment]
Akka HTTP 10.1.8 has since been released. I just tried upgrading Akka gRPC to use that new version, and indeed confirmed with the integration tests that ALPN didn't work with java11 before and does now.

This seems like a notable enough change to warrant updating the Akka HTTP dependency in Akka gRPC, so indeed I'd like to require that newer version. @ctoomey do you see any challenges there? After merging we can fairly quickly cut a new release I think.

**Comment by ctoomey** [comment]
@raboof nope I'm not aware of any challenges.
