### ISSUE TITLE
Exclude grpc-interop-testing from whitesource

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#483]
As it is only intended for internal use

**Comment by dwijnand** [comment]
Should they even be published?

I mention it because one way to resolve this (if you're feeling generous) is via https://github.com/lightbend/sbt-whitesource/issues/53.  It auto-publishes from Travis CI, so the turnaround would be quick.

**Comment by raboof** [comment]
If we can solve this by not publishing this subproject then that would indeed be the most elegant solution.

I have the sneaking suspicion that we are publishing them for a reason, though. We should definitely check ;).

**Comment by dwijnand** [comment]
I suspect the same.

**Comment by dwijnand** [comment]
Otherwise excluding is just a `whitesourceSkip := true` away.

**Comment by raboof** [comment]
It is published because the 'scripted' integration tests rely on it. I think it is helpful to run the integration tests as scripted, as that is a little more realistic. I tried configuring sbt so that it'd include this subproject in `publishLocal` but not `publish`, but didn't find a way. I'll just exclude it from whitesource for now.

**Comment by dwijnand** [comment]
(`publish := {}, deliver := file("")`)  Possibly also/just `publishTo := None`, you know know with these things.

**Comment by raboof** [comment]
Tried a few combinations but that seems to make `sbt scripted` (which depends on the artifact of this subproject) fail
