### ISSUE TITLE
Akka gRPC java client is timing out

### ISSUE THREAD

**Issue by sgurusam** [akka/akka-grpc#493]
Hello, I am a newbee in gRPC and learning right now. I am unable to figureout why example.myapp.helloworld.GreeterClient (java) client doesn't work. But, scala client works well with scala and java server. 

I performed ping-pong test by following:

Bring up server:

> sbt
> sbt> project akka-grpc-plugin-tester-java
> sbt> compile
> sbt> runMain example.myapp.helloworld.GreeterServer 

Test the client

> sbt
> sbt> project akka-grpc-plugin-tester-java
> sbt> compile
> sbt> runMain example.myapp.helloworld.GreeterClient

For Clients, I tested both with GrpcClientSettings.fromConfi as well as GrpcClientSettings.connectToServiceAt (without TLS and correct host and port). Both of them are throwing below exception

> 
> java.util.concurrent.TimeoutException
> 	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
> 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
> 	at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:84)
> 	at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:84)
> 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
> 	at scala.concurrent.package$.blocking(package.scala:142)
> 

Do anyone has ideas on why grpc client works on scala but not java?

Thanks!

**Comment by johanandren** [comment]
I just tried to repeat and on my machine it works as expected using the plugin-tester client and server, something in your environment that is already using some port or something?

**Comment by sgurusam** [comment]
Thanks @johanandren for taking a look. Port looks good. I am not sure what other environment settings can impact. For now, I will close the issue. Thanks for checking.
