### ISSUE TITLE
Back-pressure does not work.

### ISSUE THREAD

**Issue by style95** [akka/akka-grpc#499]
It seems back-pressure does not work with Akka-GRPC.

I want to fetch messages from Kafka and make them consumed by the dynamic number of clients.
I used Kafka akka stream library(alpakka).

First, I created SourceQueue with PartitionHub.

```
  val (queue, fromProducer): (SourceQueueWithCompleteAndSize[HelloReply],
                              Source[HelloReply, NotUsed]) = MeasurableSourceQueue
    .queue[HelloReply](100, OverflowStrategy.backpressure)
    .toMat(
      PartitionHub.sink((size, elem) ⇒ math.abs(elem.hashCode % size),
                        startAfterNrOfConsumers = 1,
                        bufferSize = 1))(Keep.both)
    .run()
```

And I created Kafka consumer stream and make it offer messages to the queue.

```
  val control =
    Consumer
      .atMostOnceSource(consumerSettings,
                        Subscriptions.topics("whisk.system-action"))
      .mapAsync(1) { record =>
        queue.offer(record)
      }
      .toMat(Sink.seq)(Keep.both)
      .mapMaterializedValue(DrainingControl.apply)
      .run()
```

Before a client starts, it works as expected.
No more 100 records are stored in the queue as the buffer size of the queue is 100.

When a client starts and requests the Source using the following API, it starts reading 1 message per 1 second based on throttle API.
```
    def runStreamingReplyExample(): Unit = {
      val responseStream = client.itKeepsReplying(HelloRequest("Alice"))
      val done: Future[Done] =
        responseStream
          .buffer(1, OverflowStrategy.backpressure)
        .throttle(1, 1000 milliseconds)
          .map(reply => {
            println(s"got streaming reply: ${reply.message}")
          })
          .runWith(Sink.ignore)

      done.onComplete {
        case Success(_) =>
          println("streamingReply done")
        case Failure(e) =>
          println(s"Error streamingReply: $e")
      }
    }
```

But in the Kafka consumer side, it repeatedly offers messages to the queue.
(more than 1 messages per second)
More strange part is, I monitored the size of the queue, the size is 0 most of the time.

What I am expecting is Kafka consumer offers 1 message per second when the client starts.

I am replying to the client like this:

```
  override def itKeepsReplying(
      in: HelloRequest): Source[HelloReply, NotUsed] = {
    Source
      .single(in)
      .ask[Source[HelloReply, NotUsed]](1)(actor)
      .flatMapConcat(x => x)
  }
```

**Comment by johanandren** [comment]
Hi @style95 as I said before, please use the forum for such questions and do not cross post in several places. Forum question about the same: https://discuss.lightbend.com/t/backpressure-support-with-akka-grpc/3192

**Comment by style95** [comment]
ok, sorry. I thought this is an "issue" rather than a question.
So is there any official procedures to raise an issue here or only privileged people can raise it?

**Comment by johanandren** [comment]
@style95 I was a bit quick on closing it here, I have after investigating it a bit opened up #501

**Comment by johanandren** [comment]
To clarify, backpressure does work, it just doesn't work quite how you would think.
