### ISSUE TITLE
Build for scala 2.13 as well

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#506]
Depends on
* [x] https://github.com/playframework/playframework/pull/8998 
* [x] https://github.com/scalapb/ScalaPB/issues/540

**Comment by dwijnand** [comment]
Note the diff in https://github.com/akka/akka-grpc/pull/521 for how to support for an addition Scala version is setup.

**Comment by raboof** [comment]
2.13.0-RC2 now depending on:
* [ ] https://github.com/scalapb/ScalaPB/issues/586

**Comment by dwijnand** [comment]
ScalaPB 0.9.0-M7 was been released for Scala 2.13.0.

**Comment by dwijnand** [comment]
Oh, fixed in #599, but unreleased for now.

**Comment by raboof** [comment]
Jup, we plan to release this after https://github.com/akka/akka-http/issues/2590 (unless anyone wants to do an earlier release)

**Comment by bjaglin** [comment]
I can't find 0.7.0 artifacts for scala 2.13 on maven central: https://repo1.maven.org/maven2/com/lightbend/akka/grpc/.

Is that expected?

**Comment by dwijnand** [comment]
No... thanks for the report!

@raboof probably just need to change the

```yaml
    - stage: publish
      script: sbt publish
      name: sbt publish
```

to `sbt +publish`.

**Comment by raboof** [comment]
Oops! Added #643, I'll look into pushing that one (either for 0.7.0 or a 0.7.1) somewhere next week.

**Comment by bjaglin** [comment]
@raboof I guess you decided not to publish a 2.13 artifact for 0.7.0? any idea on when you will cut 0.7.1? thanks!

**Comment by raboof** [comment]
Yeah, sorry about that! I can start cutting 0.7.1 at any time, but there's some interesting PR's that seem pretty close to being mergable, so I was waiting for those. If you have a need for 0.7.1 then I can start cutting it this week, otherwise I'd like to wait until more of those in-flight PR's are in.

**Comment by bjaglin** [comment]
No rush here, let's wait for those to get in indeed!

**Comment by jeffrey-aguilera** [comment]
Actually, sooner is better than later. This is holding up my project --- and many others --- from making the jump to 2.13.0. I would rather have the last version, but in 2.13.0 form, rather than wait for "interesting PRs".

**Comment by raboof** [comment]
I'll look into it next week!
