### ISSUE TITLE
scripted cross-scala test cannot find 2.11 artifacts

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#514]
e.g. https://jenkins.akka.io:8498/job/akka-grpc-pr-validator/800/console

This is because it was published with a timestamp (in the above case `akka-grpc-runtime_2.11-0.4.2+38-dc250492+20190124-1204`), which happens when the git repo is dirty. The question is why the git repo is considered dirty - this could happen when sources are being formatted during compilation, but it's not obvious from the build output that that is the case there.

**Comment by ennru** [comment]
Scala 2.11 is not used anymore. Closing.
