### ISSUE TITLE
Move Play-specific code to their own repo's

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#517]
A lot of the Play-specifics are already in a separate repository at https://github.com/playframework/play-grpc , but the code generation itself is still in akka-grpc.

It made sense to keep it close to the Akka code generation when the code generation API's were still evolving quickly, but we do plan to move them out. Since the Akka gRPC infrastructure allows contributing code generators from 'outside' this should be relatively feasible.

Perhaps good to finish #420 first, though.

**Comment by dwijnand** [comment]
Who knows the Play generators and could help maintain them in play-grpc?

**Comment by raboof** [comment]
I think at least myself, @renatocaval, @johanandren and (esp. when that PR is merged) @ctoomey?

**Comment by ctoomey** [comment]
Yep I could help a bit after #420, which I'll tackle again once #179  is merged. As far as that goes I've done everything except update the documentation, which I'll do soon.

**Comment by raboof** [comment]
The next step here would be to make the akka-grpc configuration API's powerful enough so Play generators can be inserted without Play-specific knowledge in akka-grpc.

This is already the case for sbt (via `akkaGrpcExtraGenerators`, i.e. https://developer.lightbend.com/docs/play-grpc/current/play/serving-grpc.html), and we should find a way to expose that for Gradle users (who currently use the `generatePlay`/`usePlayActions` gradle plugin settings) and Maven users (who currently use specific generatePlayClient/generatePlayServer/usePlayActions settings).

After that, we can move the generators themselves to their own `play-grpc-generators` artifact, and introduce a `play-grpc-runtime` to hold the parts of the runtime that hook into Play.

**Comment by raboof** [comment]
this has been done
