### ISSUE TITLE
Generate invalid code for server side in play-java

### ISSUE THREAD

**Issue by zhengcan** [akka/akka-grpc#523]
Akka gRPC Version: 0.5.0

The PR #502 and #511 introduce some conflict changes between `akka-grpc/codegen/src/main/twirl/templates/PlayJavaServer/Router.scala.txt` and `akka-grpc/runtime/src/main/scala/akka/grpc/javadsl/GrpcExceptionHandler.scala`.
These conflict changes haven't been fixed in 0.5.0, which make akka-grpc generate invalid code for play-java.

For example, in `Router.scala.txt`：
```
  public Abstract@{service.name}Router(Materializer mat) {
    this(mat, GrpcExceptionHandler.defaultMapper());
  }

  public Abstract@{service.name}Router(Materializer mat, Function<Throwable, Status> eHandler) {
    this.eHandler = eHandler;
    super(mat, @{service.name}.name);
  }
```
* `GrpcExceptionHandler.defaultMapper()` will return `Function<ActorSystem, Function<Throwable, Status>>` instead of `Function<Throwable, Status>`
* `super(..)` must be first line in ctor
* ref:
  * https://github.com/akka/akka-grpc/blame/master/codegen/src/main/twirl/templates/PlayJavaServer/Router.scala.txt

**Comment by bjaglin** [comment]
This is not specific to Java as I ran into the same issue with Scala - it looks like Play codegen is not covered by any integration test actually.

I was confused to see the `play-grpc` 0.5.0 green, but I realized versions [were not aligned across repos](https://github.com/playframework/play-grpc/blob/v0.5.0/project/plugins.sbt#L7) even though the 0.5.0 tags came almost at the same time.

**Comment by johanandren** [comment]
Yeah, there is some work in progress on that. @dwijnand I think you know the status best, maybe you could fill in something here?

**Comment by dwijnand** [comment]
It wasn't in progress originally as I thought we were trying to move away from having "Play-specific" things.

However more recently we've decided to unburden the akka-grpc repo of Play things.

Unfortunately there's some very long lived PRs that are blocking that progress, see https://github.com/akka/akka-grpc/issues/517.

**Comment by patriknw** [comment]
@johanandren Do you understand the status of this issue? Can we close it here?

**Comment by johanandren** [comment]
Play gRPC is no longer a part of this repo, so I think we can close.
