### ISSUE TITLE
Generated code hygiene

### ISSUE THREAD

**Issue by jroper** [akka/akka-grpc#552]
The code generated by akka-grpc is not very hygienic - it's very easy to create a protobuf file that, when compiled, will result in uncompilable Scala code. For example, if I have a protobuf message called `Source`, scalac resolves names in the current package before imports, so anywhere where the generated code is expecting to use `akka.stream.scaladsl.Source`, will get my protobuf `Source` message instead. And as is common with protobuf, you don't always have control over the names of the messages.

So, akka-grpc generated code should, in general, *never* use any `import` statements, rather, it should only use fully qualified class names, preferably prefixed by `_root_` for Scala code, this ensures maximum hygiene. This will ensure the classes it uses never conflict with the generate protobuf message classnames.

I encountered this problem simply by creating my own protobuf `Done` message.

**Comment by raboof** [comment]
We have to balance 2 slightly competing goals here: on the one hand we want to produce working code regardless of whatever crazy (or not so crazy) things may be found in the `.proto` definition. On the other hand, we want the generated code to look somewhat idiomatic/palatable (this is of course more important for the user-extended interfaces than for the more 'internal' generated handler code, but still a concern even there).

On that balance, i think #553 is a great improvement - spelling out the full package names is not *too* foreign and clearly solves a problem. Also prefixing `_root_`, while obviously even safer, feels like it would tip the balance and produce too foreign-looking code.

As a longer-term goal, it would be great if we could be smarter about this and only spell out the prefix for types where this is observed to be needed.

**Comment by raboof** [comment]
I think we can consider this done since #553 is merged.

While I still would like being smarter about this and only generating FQDN's when actually needed, I'm not sure that's even ticket-worthy at this point.
