### ISSUE TITLE
Missing Maven dependencies 

### ISSUE THREAD

**Issue by mckeeh3** [akka/akka-grpc#569]
### Versions used 

Akka gRPC 0.6.0

Akka version: 

### Expected Behavior

Project does not build due to missing Maven dependencies. 

### Reproducible Test Case

Create a Java Maven project following the documentation. The project will not build. Added the following dependencies to fix the problem.

        <dependency>
            <groupId>com.lightbend.akka.grpc</groupId>
            <artifactId>akka-grpc-runtime_2.12</artifactId>
            <version>${akka.grpc.version}</version>
        </dependency>

        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>${grpc.version}</version>
        </dependency>

**Comment by johanandren** [comment]
Thanks for reporting @mckeeh3 

The runtime dependency is already in the docs for maven as far as I can see:
https://developer.lightbend.com/docs/akka-grpc/current/server/walkthrough.html#setting-up

For the protobuf-java, are you sure you needed that and that there wasn't anything special you did that made it needed (I think V argued protobuf-java should be among the default transitive deps though: #565 )

**Comment by dotbg** [comment]
All required dependencies are present in the 0.8.1
@johanandren  perhaps, this issue should be closed

**Comment by raboof** [comment]
Thanks for checking!
