### ISSUE TITLE
Release 0.6.1 not in Maven Central

### ISSUE THREAD

**Issue by lomigmegard** [akka/akka-grpc#575]
The new release tagged [`0.6.1`](https://github.com/akka/akka-grpc/releases/tag/v0.6.1) is not available on Maven Central: https://mvnrepository.com/artifact/com.lightbend.akka.grpc/akka-grpc-codegen

**Comment by raboof** [comment]
Thanks, syncing now!

**Comment by raboof** [comment]
Should be there now, though some indexes might still need updating https://repo1.maven.org/maven2/com/lightbend/akka/grpc/akka-grpc-codegen_2.12/0.6.1/

**Comment by lomigmegard** [comment]
cheers :)
