### ISSUE TITLE
Use scalafmt (instead of scalariform)

### ISSUE THREAD

**Issue by ennru** [akka/akka-grpc#578]
### Short description

Akka gRPC should apply the same formatting rules as Akka by using scalafmt.

**Comment by style95** [comment]
+1 on this.
I am using Akka and have to exclude the Akka-grpc relevant module from the scalafmt check.
Especially I should unapply this compile flag: `-Ywarn-unused-import`

**Comment by raboof** [comment]
@style95 are you talking about the Akka gRPC code itself or generated code?

Both would be great contributions!

**Comment by style95** [comment]
In my case, the generated code includes "unused import" so I excluded the entire module.
Is there any good way to exclude generated codes only?

**Comment by raboof** [comment]
Closing this issue as #610 formats the Akka gRPC sources with scalafmt. I think improved formatting for the generated code might still be nice, but let's track that in a separate ticket. Anyone up to opening one?
