### ISSUE TITLE
How to configure client to allow insecure connections?

### ISSUE THREAD

**Issue by ctoomey** [akka/akka-grpc#582]
How can `GrpcClientSettings` be used to tell the client to allow insecure SSL connections, ala `curl -insecure`, for development purposes?

**Comment by raboof** [comment]
We don't support this as a feature, but for the time being I wonder if this can be achieved with `withChannelBuilderOverrides` (https://github.com/akka/akka-grpc/blob/master/runtime/src/main/scala/akka/grpc/GrpcClientSettings.scala#L225) and the suggestion from https://stackoverflow.com/questions/52540899/disabling-certificate-check-in-grpc-tls?

**Comment by ctoomey** [comment]
Thanks @raboof . For future reference here's the above translated for akka-grpc client usage:

```
  // Following is equivalent to grpcurl's -insecure flag -- disable certificate verification so
  // self-signed certs work
  val sslContext = SSLContext.getInstance("TLSv1.2")
  sslContext.init(null, InsecureTrustManagerFactory.INSTANCE.getTrustManagers, new java.security.SecureRandom())

  val settings = GrpcClientSettings
    .connectToServiceAt("localhost", 443)
    .withSSLContext(sslContext)
    .withTls(true)
```
