### ISSUE TITLE
Module to generate HTTP+JSON endpoints based on .proto annotations

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#605]
https://github.com/lightbend/stateful-serverless/blob/master/src/protocols/frontend/example/shoppingcart/shoppingcart.proto#L46
https://github.com/lightbend/stateful-serverless/blob/master/src/backend/core/src/main/scala/com/lightbend/statefulserverless/HttpApi.scala

**Comment by johanandren** [comment]
Duplicate of #238 ?

**Comment by raboof** [comment]
agreed
