### ISSUE TITLE
Gradle plugin not publishing generated Java sources in a location an IntelliJ project knows of

### ISSUE THREAD

**Issue by orendain** [akka/akka-grpc#617]
### Version

- Using akka-grpc-gradle-plugin, version **0.6.2**
- Using Java 1.8

### Expected Behavior

`gradlew build` should publish classes in a location that IntelliJ picks up on.  

### Actual Behavior

A vanilla Gradle project, as described by the docs (including the akka-grpc-quickstart-java project), publishes classes (via `gradlew build`) in a location that IntelliJ isn't made aware of.

Specifically, IntelliJ cannot resolve:
- Any of the generated proto classes
- `ProtobufSerializer` in `import akka.grpc.ProtobufSerializer`
- `GoogleProtobufSerializer` in `import akka.grpc.javadsl.GoogleProtobufSerializer`

Gradle correctly builds and runs, but IntelliJ isn't able to recognize certain sets of classes.

**Comment by orendain** [comment]
Currently, my sad workaround is generating the different proto/grpc classes (via regular `gradle build`), and copying them (or symlink) from the `build` directory out to `src` where it can be picked up by Intellij.

If anyone is having the same problem and modified the plugin to work, or has a cleaner IntelliJ config adjustment for having IntelliJ play nice with the plugin, a share would be appreciated 😃 .

**Comment by raboof** [comment]
It would be great if someone can figure this out! I'm not much of a gradle expert either, I'm afraid...

**Comment by johanandren** [comment]
Curious thing though: I just created a gradle project from scratch and loaded that into IntelliJ and it does pick up `build/generated/source/proto/main/*` but makes it a sources root, not generated sources like one would want.

Looks like it expects the directory to be `build/generated/sources` rather than `source` because when building that appears as well, perhaps that is the problem.

**Comment by johanandren** [comment]
Looking at the gradle plugin it does something weird, it only adds the generated directories to the `sourceSets` if the project is a Scala project, that is perhaps a clue in a different direction.

**Comment by orendain** [comment]
@johanandren Indeed - I found the same thing: generated directories are added only for scala projects and not for java ones.

**Comment by orendain** [comment]
Updated title to better reflect the exact issue we're discussing.  I made a change to the gradle-plugin, rebuilt it, and have things working as expected.  Will open up a PR for this.
