### ISSUE TITLE
generated Java code requires "option java_multiple_files = true"

### ISSUE THREAD

**Issue by kgignatyev** [akka/akka-grpc#619]
given proto
```
syntax = "proto3";

package imani.mobile_api;

option java_package = "imani.mobile_api";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";



message LocalDateTime {
    google.protobuf.Timestamp timestamp = 1;
    sint32 offset = 2;
}
....
```

and  this config

```
                <groupId>com.lightbend.akka.grpc</groupId>
                <artifactId>akka-grpc-maven-plugin</artifactId>
                <version>0.6.2</version>
                <configuration>
                    <protoPaths>
                        <!--                        <protoPath>/usr/local/Cellar/protobuf/3.7.1/include</protoPath>-->
                        <protoPath>../common/src/main/proto</protoPath>
                    </protoPaths>
<!--                    <language>Scala</language>-->
                    <generateClient>true</generateClient>
                    <generateServer>true</generateServer>

                    <generatorSettings>
<!--                        <generatorSetting>flat_package</generatorSetting>-->
                        <generatorSetting>server_power_apis</generatorSetting>
                    </generatorSettings>

                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

java code is generated in correct package but references non-existent package with capitlized name of proto file (imani_public) 

```
// Generated by Akka gRPC. DO NOT EDIT.
package imani.mobile_api;

import akka.grpc.ProtobufSerializer;
import akka.grpc.javadsl.GoogleProtobufSerializer;

public interface ImaniMoneyService {
  
  java.util.concurrent.CompletionStage<imani.mobile_api.Imani_public.MoneyTransferResponse> send_money(imani.mobile_api.Imani_public.MoneyTransferRequest in);
 ```

![image](https://user-images.githubusercontent.com/868783/61009357-477df580-a327-11e9-9105-50d416e93524.png)
 
if I specify language Scala, then code is compilable, but it is in a wrong extra sub package named after proto file

![image](https://user-images.githubusercontent.com/868783/61009509-a9d6f600-a327-11e9-9cd6-90a1d8cc491b.png)

**Comment by johanandren** [comment]
Strange. maven Java and Scala verification is part of our CI-jobs so this I wonder if there is something special about this setup causing it. Can you check without using underscore in the package name and see if that is what is causing it?

**Comment by raboof** [comment]
It might have been good to file this as 2 separate issues.

## For Java:

> maven Java and Scala verification is part of our CI-jobs so this I wonder if there is something special about this setup causing it

Perhaps we are not testing the situation where the `java_package` option is used?

Would you be interested in testing further and perhaps preparing a PR, @kgignatyev ?

## For Scala:

> code is compilable, but it is in a wrong extra sub package named after proto file

Hmm, this suggests the `flat_package` option (described at https://scalapb.github.io/customizations.html) is not passed along correctly. Passing this option explicitly is described at https://doc.akka.io/docs/akka-grpc/current/buildtools/maven.html#generating-server- , but I would have expected this to be the default. Could you check if the extra sub package disappears when you add `flat_package` explicitly?

**Comment by kgignatyev** [comment]
yes, when I added flat_package explicitly the subpackage disappeared, but Java issue is present, please run the attached project that reproduces the issue 
this demonstrates wrong java code

mvn -f pom-wrong-java.xml clean install

this generates subpackage

mvn -f pom-scala-wrong-subpack.xml clean install

this seem to be well

mvn -f pom-scala-well.xml clean install

[akka-grpc-repro.zip](https://github.com/akka/akka-grpc/files/3383249/akka-grpc-repro.zip)

**Comment by raboof** [comment]
> when I added flat_package explicitly the subpackage disappeared

OK, I think that should be the default, moved that to its own issue at #623

> mvn -f pom-wrong-java.xml clean install

Hmm, it does work when I specify `option java_multiple_files = true`, and I see all our examples have that option set. Would you be interested in preparing a PR to improve the Java code generation in Akka gRPC to work also for proto files without that option?

**Comment by raboof** [comment]
(I took the liberty of updating the issue title to be more accurate based on this new information)

**Comment by kgignatyev** [comment]
I prefer working with Scala and came across problem with Java just by chance. Ido not really need it for current project (and java_multiple_files = true looks like OK workaround)  , I wish I had time to work on PR this time.

I suggest that in meantime grpc plugin to stop parsing protos and throw error when language is Java and "option java_multiple_files = true" is not present in proto.

**Comment by raboof** [comment]
> I do not really need it for current project (and java_multiple_files = true looks like OK workaround) , I wish I had time to work on PR this time.

Makes sense!

> in meantime grpc plugin to stop parsing protos and throw error when language is Java and "option java_multiple_files = true" is not present in proto

That sounds like a useful first step!

**Comment by sebastian-alfers** [comment]
@kgignatyev It seems you are using an old version of the plugin (`0.6.2`). Can you upgrade to something more recent and confirm this is still a problem? The [quickstart](https://developer.lightbend.com/guides/akka-grpc-quickstart-java/) provides `<version>${akka.grpc.version}</version>` as a value for `<artifactId>akka-grpc-maven-plugin</artifact`.

**Comment by johanandren** [comment]
With akka-grpc 2.3.0 the shared reproducer compiles fine with `mvn -f pom-wrong-java.xml clean install` (as well as the other two pom versions in there) so I think we can close this issue.
