### ISSUE TITLE
Akka grpc gradle plugin: Compatibility with Java 8

### ISSUE THREAD

**Issue by lukasito** [akka/akka-grpc#635]
### Versions used 

Gradle version: 5.5.1
JDK: 8
com.lightbend.akka.grpc.gradle: 0.7.0

Akka version: 2.5.22

### Expected Behavior

Akka grpc gradle plugin is compatible with JDK8. Method used in plugin `Files.writeString`  is since JDK 11.

### Actual Behavior

Akka grpc gradle plugin is not compatible with JDK8. `Files.writeString` should be replaced with e.g. `Files.write​(Path path, Iterable<? extends CharSequence> lines, OpenOption... options)`

### Relevant logs

* What went wrong:
A problem occurred evaluating root project 'xxx'.
> Failed to apply plugin [id 'com.lightbend.akka.grpc.gradle']
   > No signature of method: static java.nio.file.Files.writeString() is applicable for argument types: (sun.nio.fs.WindowsPath, String, java.nio.file.StandardOpenOption...) values: [C:\Users\xxx\.gradle\caches\modules-2\files-2.1\com.lightbend.akka.grpc\akka-grpc-codegen_2.12\0.7.0\5401fb7fd369a7dba6d3b9f63be21ccf010758d8\akka-grpc-codegen_2.12-0.7.0-assembly.bat, ...]
     Possible solutions: toString(), toString()

### Reproducible Test Case
Just add plugin to your gradle project while JAVA_HOME is JDK8 (so gradle is using this version)

**Comment by raboof** [comment]
Thanks for the report! Too bad this wasn't caught by https://travis-ci.org/akka/akka-grpc/jobs/559961051 .

Would you be interested in preparing a PR? It'd probably also be good to update the Travis configuration so those integration tests run on JDK8.

**Comment by lukasito** [comment]
Sorry, I'm not familiar with Travis configuration. 😞

**Comment by raboof** [comment]
Strange, travis *should* already be using jdk8. testing this in https://travis-ci.org/akka/akka-grpc/builds/560385262

**Comment by lukasito** [comment]
Well, the problem is that it's groovy, so it won't fail during compile time. This will only occur on windows machine when plugin is applied.

**Comment by raboof** [comment]
> This will only occur on windows machine when plugin is applied.

Aaah missed that... nothing we can do there right now then

**Comment by lukasito** [comment]
btw, can you add `gradle` label? #636 here as well, thx.
