### ISSUE TITLE
akk-grpc generates broken stubs due to #432

### ISSUE THREAD

**Issue by ElkMonster** [akka/akka-grpc#652]
### Versions used 

Akka gRPC 0.7.0

Akka version: doesn't matter (I believe)

### Expected Behavior

Comments in .proto files should be included in generated stubs in a way that the resulting code compiles.

### Actual Behavior

Under certain conditions, the generated code will not compile. Consider this:

This comment in a .proto file
```
service MediaService {
    ///////////////////////////////////////////////////// SOURCES
    …
```
results in these lines in the generated stub
```
/**
 */////////////////////////////////////////////////// SOURCES
 *
 */
trait MediaService { …
```
The comment from the .proto file was simply copied except for the leading two dashes which make up the actual comment. As a result, the comment block in the resulting Scala (or Java) source prematurely ends, leading to a syntax error in the next line (due to an unexpected `* `).

**Comment by ElkMonster** [comment]
P.S.: The cause is the problem is probably https://github.com/akka/akka-grpc/issues/432 (Include .proto comments in generated gRPC stubs).

**Comment by raboof** [comment]
Good observation, thanks! Looks like we need to add some escaping - @bjaglin would you be interested in that? Or @ElkMonster yourself?

**Comment by ElkMonster** [comment]
Okay, I'll have a look into it.

**Comment by ElkMonster** [comment]
I'm don't really know how one would usually do this… should I add another method here with my test case comment
https://github.com/akka/akka-grpc/blob/f6536403a5cccecb6398ec0485e0ba45f9fa994f/plugin-tester-scala/src/main/protobuf/helloworld.proto#L13-L30
and extend `GreeterServiceImpl` accordingly? Or just extend one of the existing comments (line 18?)?

**Comment by bjaglin** [comment]
ScalaPB is doing the escaping, so I think the fix should be upstream in https://github.com/scalapb/ScalaPB/blob/48a89535c007f194dfc173ea7489bd870343bcaa/compiler-plugin/src/main/scala/scalapb/compiler/DescriptorImplicits.scala#L963-L971.

So I would start by adding your comment as a test case [there](https://github.com/bjaglin/ScalaPB/blob/ceebc91a36929f4a595bc4c5ed7be65cd4fba59d/e2e/src/main/protobuf/comments.proto) to fix the escaping there.

I can assist if needed @ElkMonster !

**Comment by bjaglin** [comment]
Scratch my suggestion above - I had a closer look at your comment, and it seems that escaping within the comment itself might not make sense as it's the combination of the comment block header and the content that triggers the problem. And it does look like [ScalaPB handles this case](https://github.com/scalapb/ScalaPB/pull/534/files#diff-6d48ba09f4ba437b8fa7b89d7355d251R1892), so the fix might be to replicate this logic in the twirl templates here.

**Comment by ElkMonster** [comment]
@bjaglin Sorry, but would you mind to take over? I'm not really getting anywhere because I'm pretty unfamiliar with the whole project and its setup. It will probably take me hours to come up with something that works… to many stones in my way…

**Comment by bjaglin** [comment]
@ElkMonster sure, I'll have a look today

**Comment by bjaglin** [comment]
https://github.com/akka/akka-grpc/pull/653
