### ISSUE TITLE
Gradle plugin fails on task generateProto when using Windows 10

### ISSUE THREAD

**Issue by hithran** [akka/akka-grpc#669]
### Versions used 

akka-grpc-gradle-plugin:0.7.1

### Expected Behavior

Have it generate the akka grpc files

### Actual Behavior

Throws a FileNotFoundException

### Relevant logs

```
> Configure project :interface
[task ':interface:assemble', task ':interface:assembleDist', task ':interface:build', task ':interface:buildDependents', task ':interface:buildEnvironment', task ':interface:buildNeeded', task ':interface:check', task ':interface:classes', task ':interface:clean', task ':interface:compileJava', task ':interface:compileScala', task ':interface:compileTestJava', task ':interface:compileTestScala', task ':interface:components', task ':interface:dependencies', task ':interface:dependencyInsight', task ':interface:dependentComponents', task ':interface:distTar', task ':interface:distZip', task ':interface:help', task ':interface:installDist', task ':interface:jar', task ':interface:javadoc', task ':interface:model', task ':interface:processResources', task ':interface:processTestResources', task ':interface:projects', task ':interface:properties', task ':interface:run', task ':interface:scaladoc', task ':interface:startScripts', task ':interface:tasks', task ':interface:test', task ':interface:testClasses']

> Task :interface:extractIncludeProto UP-TO-DATE
> Task :interface:extractProto UP-TO-DATE
> Task :interface:generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':interface:generateProto'.
> protoc: stdout: . stderr: D:\interface\src\main\proto: warning: directory does not exist.
  D:\interface\app\protobuf: warning: directory does not exist.
  D:\interface\app\proto: warning: directory does not exist.
  Exception in thread "main" java.io.FileNotFoundException: \Users\<User>\AppData\Local\Temp\akka-grpc-gradle6625443006303105175.log (Het systeem kan het opgegeven pad niet vinden)
  	at java.base/java.io.FileOutputStream.open0(Native Method)
  	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
  	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
  	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
  	at java.base/java.io.PrintWriter.<init>(PrintWriter.java:208)
  	at java.base/java.io.PrintWriter.<init>(PrintWriter.java:248)
  	at akka.grpc.gen.FileLogger.<init>(Logging.scala:35)
  	at akka.grpc.gen.Main$.$anonfun$logger$1(Main.scala:48)
  	at scala.Option.map(Option.scala:163)
  	at akka.grpc.gen.Main$.delayedEndpoint$akka$grpc$gen$Main$1(Main.scala:48)
  	at akka.grpc.gen.Main$delayedInit$body.apply(Main.scala:14)
  	at scala.Function0.apply$mcV$sp(Function0.scala:39)
  	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
  	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
  	at scala.App.$anonfun$main$1$adapted(App.scala:80)
  	at scala.collection.immutable.List.foreach(List.scala:392)
  	at scala.App.main(App.scala:80)
  	at scala.App.main$(App.scala:78)
  	at akka.grpc.gen.Main$.main(Main.scala:14)
  	at akka.grpc.gen.Main.main(Main.scala)
  --akkaGrpc_out: protoc-gen-akkaGrpc: Plugin failed with status code 1.

```

### Reproducible Test Case

Define a protofile and use the gradle plugin. My configuration:
```
buildscript {
    repositories {
        mavenLocal()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'gradle.plugin.com.lightbend.akka.grpc:akka-grpc-gradle-plugin:0.7.1'
    }
}
plugins {
    id 'scala'
    id 'application'
}
apply plugin: 'com.lightbend.akka.grpc.gradle'
akkaGrpc {
    language = "Scala"
    generateClient = false
    generateServer = true
}
repositories {
    mavenLocal()
    mavenCentral()
}
```

## Possible fix
I've created a fix that works for my machine @ https://github.com/hithran/akka-grpc/commit/e8c71936f94c787f79c1654c78557f376b1eae4c
But I'm curious to here if it still works for @mlangc who originally wrote the fix for logging.

**Comment by mlangc** [comment]
Hi @hithran, I didn't verify, but I'm pretty sure that your fix should work for me. What version of Windows are you using?

The reason why I forgot to prefix the path with the drive letter is that on the laptop I'm working on, the logs are written to a path somewhere on `C:\` (which seems to be implicitly added to the path if not specified), whereas on your laptop, it seems to be somewhere on `D:\`. Thus your fix definitely makes sense!

**Comment by hithran** [comment]
I'm on Microsoft Windows [Version 10.0.17134.950], my project is on `D:\`, but the temp dir is on `C:\`.
In my previous tries I had some trouble getting the version number aligned to do a proper test, but now i figured out how to get the gradle-plugin to use the snapshot version of the akka-grpc library. I got to the point it is no longer complaining about the missing log file, but I run into a new issue.
Seems that the options should be separated by `:`, which is also what is used in the drive letter.
```
> protoc: stdout: . stderr: D:\backend\src\main\proto: warning: directory does not exist.
  D:\backend\src\main\protobuf: warning: directory does not exist.
  D:\backend\app\protobuf: warning: directory does not exist.
  D:\backend\app\proto: warning: directory does not exist.
  /Users/<User>/AppData/Local/Temp/akka-grpc-gradle1239371440951962183.log,flat_package:D:\backend\build/generated/source/proto/main/akkaGrpc/: Invalid argument
```
I'll try to find out what is going on, but any pointers are welcome :)

**Comment by hithran** [comment]
Without the logfile option it works like a charm.. ^^

**Comment by mlangc** [comment]
@hithran I've already had a discussion about the log file here: https://github.com/akka/akka-grpc/pull/622#issuecomment-510509822

@raboof Maybe we can drop the logfile option if and only if we are on Windows and the path to the logfile is not on `C:`?

**Comment by mlangc** [comment]
Or we could try to create the temporary log file on `C:` if possible by using [java.io.File#createTempFile(java.lang.String, java.lang.String, java.io.File)](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#createTempFile-java.lang.String-java.lang.String-java.io.File-). In the rare event that this is not possible, we can simply disable logging altogether.

**Comment by hithran** [comment]
The logging file is created by using https://docs.oracle.com/javase/8/docs/api/java/io/File.html#createTempFile-java.lang.String-java.lang.String-java.io.File-. The file is created there with the name on C:\Users\<User>\AppData\Local\Temp, only the path to the logfile is somehow mangled when it is passed to protoc. But there is no information inside the logfile, it is just an empty file.

The inclusion of the drive letter only fixes the file not found issue, but introduces the new error which is the `Invalid argument`

**Comment by mlangc** [comment]
Ahh... so your home directory is on `C:`, but your build directory is on `D:` right? Can you try if the error with the unpachted plugin (that is without your changes) goes away if you move the build to `C:`?

**Comment by hithran** [comment]
Correct, home directory on `C:`, project on `D:`. I'll try and come back with the result

**Comment by hithran** [comment]
It works with the unpatched plugin when I have my project on `C:` 😲.
I just noticed a file called C in my root folder which is the logfile that is used, containing:
```
[info] Got the log file working yay! Some(C)
[info] Generating Akka gRPC service interface for com.example.Greeter
[info] Generating Akka gRPC service handler for com.example.Greeter
```
Where the Some(C) is what is gathered from parameters in the Main.scala of the code generator.

**Comment by mlangc** [comment]
Yes, good analysis, it seems that the plugin splits on `:` indeed, and that paths without a drive letter on Windows inherit the drive letter from the current working directory. Therefore we have two options as far as I can see:

* Find out if we can escape the `:` somehow, so that the full path including the drive letter is correctly passed to the plugin
* Try by all means to create the temporary logfile on the same drive as the current working directory, or if this is not possible for some reason, disable logging altogether.

@hithran what do you think?

**Comment by hithran** [comment]
I've tried the simple ways of just quoting the path with single or double quotes but the problem remained. I'm not sure there are other (easy) ways to escape the path in such a way that the plugin is still able to use it. Seems like a lot of work.

If tested with my project on `D:\` and creating the log file on `D:\` but I'm not able to get that to work, I run into the same issues. There is some weird magic going on when the project is on `C:\` of which I'm not able to figure how that seems to work...

Another solution would be to create the logfile in the (Gradle) build directory in the project folder.
I've created a working solution by using `File logFile = File.createTempFile("akka-grpc-gradle", ".log", project.buildDir)` and the assumption of the build directory: `option "logfile=build/${logFile.name}"`.
Which can be combined with `Path toLogile = project.projectDir.toPath().relativize(logFile.toPath())` to remove the assumption on the name "build", but I'm not sure that is much of a problem.

Which was fine as long as the build directory existed, once I threw away the build directory, gradle was no longer able to read in the project configuration because it stated that a file must be created in the build directory.

So then I just used 'build/akka-grpc-gradle.log' as path and everything is happy.

I do not know how to defer the creation of the logfile until the plugin is executed, instead of on configuration. 

But all in all, I think that creating the logfile in the build directory and using a relative path will solve the drive letter and having to escape the `:` issues and provides a working solution on all OSes.

**Comment by hithran** [comment]
Found out what the magic is behind it working when the project is on `C:\`: [Windows file path formats](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats). Without a drive letter it will search from the root of the current file system, in this case `C:`.
I didn't know this is supported.

**Comment by mlangc** [comment]
Yea, I was already suggesting that [here](https://github.com/akka/akka-grpc/issues/669#issuecomment-523751522), but it's nice that you found some official documentation for this feature.

@hithran if you create a PR including the fix you have suggested above, I can help with review and testing.

**Comment by raboof** [comment]
Thanks for this great collaboration, looks like a wonderful outcome!

**Comment by style95** [comment]
It seems same thing happens when the plugin is used in a subproject.
It looks for the `build` directory in a project root first.
If I manually create `build` directory under the root directory, it complains the log file does not exist in `{PROJECT_ROOT}/{SUBPROJECT}/build/akka-grpc-gradle-plugin.log`.

If I "touch" the file, finally the plugin(gradle build) works.
I suspect this case is not properly supported.

Is anyone facing the same issue?

**Comment by burbaki** [comment]
> It seems same thing happens when the plugin is used in a subproject.
> It looks for the `build` directory in a project root first.
> If I manually create `build` directory under the root directory, it complains the log file does not exist in `{PROJECT_ROOT}/{SUBPROJECT}/build/akka-grpc-gradle-plugin.log`.
> 
> If I "touch" the file, finally the plugin(gradle build) works.
> I suspect this case is not properly supported.
> 
> Is anyone facing the same issue?
> I am using both linux and Mac.

I've faced with the same error when using sub-project with akka-grpc depenency

**Comment by mlangc** [comment]
I'm willing to help anyone who submits a PR fixing this by reviewing and testing... unfortunately I don't have the resources to look into this myself at the moment.

**Comment by maasg** [comment]
Re:  https://github.com/akka/akka-grpc/issues/669#issuecomment-540422800
Same here. 
```
> protoc: stdout: . stderr: Exception in thread "main" java.io.FileNotFoundException: build/akka-grpc-gradle-plugin.log (No such file or directory)
```
I'm introducing akka-grpc in a sub-project. (Dev on Linux).

**Comment by raboof** [comment]
It looks like there's a workaround posted in #786 - though of course we'd love help on an actual fix :)
