### ISSUE TITLE
grpcClient service discovery is not retried if the first lookup call returns no target

### ISSUE THREAD

**Issue by fredfp** [akka/akka-grpc#670]
The service lookup is never retried if it returns an empty list of target.

In my case this happens using `akka-dns` discovery mechanism to discover kubernetes services.

One should not expect the kubernetes resources to be deployed in any particular order. 

Consequently, service lookup should be retried if it returns an empty list of targets.

**Comment by fredfp** [comment]
@johanandren is 0.7.2 due soon? I'd love to have this released...

**Comment by johanandren** [comment]
Not planned, we have been very busy with the Akka 2.6 work, I'll see if we can get 0.7.2 out soonish.

**Comment by johanandren** [comment]
0.7.2 is available on maven central now.

**Comment by fredfp** [comment]
Fantastic, thank you @johanandren !
