### ISSUE TITLE
Don't put generated sources in sourceManaged

### ISSUE THREAD

**Issue by jroper** [akka/akka-grpc#672]
sbt-protoc likes to completely own directories it writes to, when it runs, it first deletes all the old files from them. While that behavior can be turned off, it's good because otherwise sbt-protoc will leave stale files (eg, if you change the name of a message, the generated classes for the old message) lying around. But it does mean that you should never tell sbt-protoc to output to a shared directory. sbts `sourceManaged` directory is a shared directory, so if you have another sbt plugin that writes to it (eg, the sbt-buildinfo plugin), then you'll get very weird intermittent errors (because source generators run in parallel) where sbt-protoc will delete the files just generated by the other source generating plugin.

sbt-protoc doesn't actually specify an output directory, it requires the users to do that, but akka-grpc does. Akka grpc must define its own source directory to output to. I recommend using:

```scala
crossTarget.value / "akka-grpc" / Defaults.nameForSrc(configuration.value.name)
```

If you use this, you'll also have to add that directory to the `managedSourceDirectories` setting.

**Comment by a1kemist** [comment]
I just ran into this while using akka-grpc with sbt-buildinfo.

It seems like this [workaround](https://github.com/thesamet/sbt-protoc/issues/92#issuecomment-511620471) would be an easy fix, but it causes other issues in my use case.

related to thesamet/sbt-protoc/issues/92
