### ISSUE TITLE
akka-grpc generator

### ISSUE THREAD

**Issue by Tochemey** [akka/akka-grpc#681]
Hello

I would like to know whether one can pass the options of [protoc](https://helpmanual.io/help/protoc/). The reason I asked this question is that when I run the `akka-grpc:generate` some of the google proto definitions where not found like for instance `field_mask.proto`, `empty.proto`.

**Comment by raboof** [comment]
Indeed we don't currently include the standard Google classes/proto's by default. The recommended approach is to add them to your build explicitly, but see also #565 

Closing this for now but feel free to re-open or start a thread on https://discuss.akka.io if there's more to discuss!

**Comment by Tochemey** [comment]
Thank you for the response. However I have observed that when you set the `protoPath` it does not recursively go through the subfolders of the given folder which can be also an issue

**Comment by raboof** [comment]
> I have observed that when you set the protoPath it does not recursively go through the subfolders of the given folder which can be also an issue

Hmm, is that with the maven plugin? A quick look at the code suggested it is scanning for `**/*.proto` so that would suggest it is intended to go into subfolders. So that doesn't seem to be working?

**Comment by Tochemey** [comment]
Yeah. It is with the maven plugin.

**Comment by raboof** [comment]
Could you open a specific ticket where we can track this? Would you be interested in having a closer look yourself?

**Comment by Tochemey** [comment]
Let me give it more tries and see the various possibilities. Maybe I am doing something wrong. However when necessary I will create a ticket for that when necessary.

**Comment by Dr-Nikson** [comment]
> The recommended approach is to add them to your build explicitly, but see also #565

Hello! I'm facing same issue. Could you provide more information how to include these protos to my build?

**Comment by Dr-Nikson** [comment]
> The recommended approach is to add them to your build explicitly, but see also #565

@raboof 

Hello! I'm facing same issue. Could you provide more information how to include these protos to my build?

**Comment by raboof** [comment]
Find the ones you need in https://github.com/protocolbuffers/protobuf/tree/master/src/google/protobuf, download and put them alongside your projects' .proto resources

**Comment by Dr-Nikson** [comment]
@raboof I see..) Thanks)

PS
I hope there will be some support for google protos and for including them from artifacts. Unfortunately I'm not very experienced with this stuff to provide any help\PR's.
