### ISSUE TITLE
Multiply protoPaths not compiling properly

### ISSUE THREAD

**Issue by Dr-Nikson** [akka/akka-grpc#686]
### Versions used 

Akka version: 2.5.22
akka-grpc-runtime: 0.7.1
akka-grpc-maven-plugin: 0.7.1

### Expected Behavior

```
<protoPaths>
  <protoPath>src/main/proto</protoPath>
  <protoPath>../../protos/src/main/proto</protoPath>
</protoPaths>
```

I've configured two protoPaths and I'm expecting that plugin will look for all proto files before compilation starts. One of my protoPaths contains google prototobuf types, second protoPath contains my own protos based on the first ones.

### Actual Behavior

Compilation fails because it can't find proto files from one path while compiling another:

```google/protobuf/timestamp.proto: File not found.```

**Comment by raboof** [comment]
Good observation! Would you be interested in trying to fix this and testing whether that works? It looks like in `GenerateMojo.scala` the list of paths should be passed into `generate` instead of calling `generate` for each path separately.

**Comment by jewertow** [comment]
I could take care of this issue.

**Comment by Tochemey** [comment]
Hello, please what is the outcome of this issue. I am facing the same issue too

**Comment by jewertow** [comment]
I'm working on this issue.
