### ISSUE TITLE
Convenient descriptor access

### ISSUE THREAD

**Issue by jroper** [akka/akka-grpc#710]
protoc and ScalaPB by default generate protobuf descriptor objects, which are useful in many cases, such as when providing reflection support. Akka gRPC could provide access to these on its companion objects, eg:

```scala
object MyService {
  lazy val scalaDescriptor: _root_.scalapb.descriptors.ServiceDescriptor = MyServiceProto.scalaDescriptor.services.filter(_.name == "MyService").head
  lazy val javaDescriptor: _root_.com.google.protobuf.Descriptors.ServiceDescriptor = MyServiceProto.javaDescriptor.findServiceByName("MyService")
  ...
}
```

Making the companion object implement a trait that provides these methods would also be great, as this would make it more convenient to provide and use integrations, such as HTTP transcoding or reflection support, you'd only have to pass the companion object to the service and the integration would then take care of the rest.

**Comment by viktorklang** [comment]
Great suggestion, James!

`lazy val scalaDescriptor: _root_.scalapb.descriptors.ServiceDescriptor = MyServiceProto.scalaDescriptor.services.find(_.name == "MyService").get`

**Comment by viktorklang** [comment]
Looks like it should be possible to add `serviceDescriptor.getFile.fileDescriptorObjectName` to the Service-class and then do:

```scala
  lazy val scalaDescriptor: _root_.scalapb.descriptors.ServiceDescriptor = @{service.fileCompanionProtoName}.scalaDescriptor.services.find(_.name == "@{service.name}").get
  lazy val javaDescriptor: _root_.com.google.protobuf.Descriptors.ServiceDescriptor = Option(@{service.fileCompanionProtoName}.javaDescriptor.findServiceByName("@{service.name}")).get
```

in ApiTrait.scala.txt (and similar for ApiInterface.scala.txt), then add an interface/trait which ApiTrait/ApiInterface extends which has a scalaDescriptor/javaDescriptor method.

Won't be able to address this myself right now, but this should point someone in the right direction.

**Comment by raboof** [comment]
I think this is now done through #654
