### ISSUE TITLE
Investigate how to deal with extra clients options

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-grpc#72]
At client side one may need to tweak how the client should work. 

The `grpc-java` implementation has `with` methods, e.g.: `withCompression`, `withExecutor`, `withInterceptors`, etc. Those methods are added to the stub and returns a new tweaked stub.

We could have something similar or take an approach similar to Lagom's `ServiceCall`. To be discussed and analysed.

**Comment by johanandren** [comment]
This was fixed by #201
