### ISSUE TITLE
Service discovery lookup failure should either be retried or fail the promise

### ISSUE THREAD

**Issue by chbatey** [akka/akka-grpc#728]
If service discovery fails e.g. due to a timeout the promise is not completed with failure

https://github.com/akka/akka-grpc/blob/master/runtime/src/main/scala/akka/grpc/internal/NettyClientUtils.scala#L43

It is in the case of no hosts are returned or it gets past discovery and the channel fails.

If it is failed with a known exception for a lookup timeout then it can be re-created here automatically: https://github.com/akka/akka-grpc/blob/master/runtime/src/main/scala/akka/grpc/internal/ClientState.scala#L101

**Comment by tayvs** [comment]
It make sense to add some readiness health check. This health check can be used at kubernetes and other system. What do you think?

**Comment by raboof** [comment]
> It make sense to add some readiness health check. This health check can be used at kubernetes and other system. What do you think?

I think this is implementation-dependent: when k8s ready/health checks are failing, the node will be taken out of rotation and eventually killed/restarted. When a downstream gRPC service is unavailable, that may or may not be sufficient reason to cause such a drastic effect. On many cases the service can keep running, even if with degraded performance. Perhaps we could consider making it easy to contribute a health/readiness check that tracks a downstream gRPC service's availability to https://doc.akka.io/docs/akka-management/current/healthchecks.html. I think that is outside the scope of this issue though - if you're interested in this, feel free to open up another issue!

**Comment by tayvs** [comment]
Yes, it's out of scope. But I found that you try to re establish connection with backoff. So we would already have client with no connection under the hood and we even can't figure it out. In that case readiness health check would be very helpful. And I want to use kubernetes readiness check on start and do not route a traffic on this service to avoid failing of some requests. I'll create an issue)

**Comment by raboof** [comment]
This has been refactored as part of #811
