### ISSUE TITLE
Remove unnecessary printout of gradle tasks on plugin apply

### ISSUE THREAD

**Issue by kudlatykaskader** [akka/akka-grpc#735]

**Comment by raboof** [comment]
Good one - would you be interested in picking this up?

**Comment by jewertow** [comment]
What exactly do you mean? Could you paste logs and say when you get it?

**Comment by raboof** [comment]
There is a "println project.getTasks()" in
https://github.com/akka/akka-grpc/blob/master/gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPlugin.groovy
, probably it?

**Comment by jewertow** [comment]
@raboof Thanks for giving the opportunity to make the first change in that project.

**Comment by raboof** [comment]
Thanks for the PR!

**Comment by kudlatykaskader** [comment]
Great! 
Sorry, I had notifications turned off and didn't saw that you picked it.
