### ISSUE TITLE
Binary compatibility promise

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#761]
We are gearing up for Akka 1.0 early 2020.

One thing we need to decide on is the level of binary compatibility we want to promise.

In contrast to for example Akka and Akka HTTP, we mainly see Akka gRPC used 'directly' in non-library projects. A notable exception is https://doc.akka.io/docs/alpakka/current/google-cloud-pub-sub-grpc.html .

There are 3 forms of binary compatibility that are potentially interesting:

* If you have an application that uses a library that uses Akka gRPC X to generate code, and also another library that uses Akka gRPC X+1 to generate code, should you be able to run these side-by-side in a project using Akka gRPC X+1 (or later)?
* If you have a 'user' library that has a dependency of a 'deeper' library that was built by Akka gRPC X, and there is a newer version of that 'deeper' library that was built with Akka gRPC X+1, should an application be allowed to upgrade the 'deeper' library without having to recompile/upgrade the 'user' library?
* If you are using a build system plugin that uses akka-grpc (such as [play-grpc](https://github.com/playframework/play-grpc), should it be possible to update akka-grpc in your build without also updating play-grpc?

In technical terms, these translate to:
* binary compatibility of the akka-grpc-runtime library
* binary compatibility of the generated code across versions of Akka gRPC
* binary compatibility of the build system plugin components

I think the second and third forms of binary compatibility do not seem necessary for Akka gRPC.

The first we should likely uphold to a certain degree, though perhaps we can still identify parts of the runtime API that do not need such strong guarantees.

**Comment by ennru** [comment]
The rules should point to [Akka's page](https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html) about it.

**Comment by ignasi35** [comment]
> I think the second and third forms of binary compatibility do not seem necessary for Akka gRPC.

I think I agree. IIUC, this means a user of `play-grpc` stuck on version `akka-grpc`'s `codegen` version `X` would be able to use the generated code with `runtime` X+1.

If that's the case you had in mind, then I think we agree.

**Comment by ignasi35** [comment]
Hi @raboof, I've noticed https://github.com/akka/akka-grpc/pull/900 and wondered what's left... Do you have an open list of areas that need reviewing?

**Comment by raboof** [comment]
I think we've been working towards this steadily over the last few releases. I don't have any particular area's that I know need work, so I think there's 4 things we can do:

1) I think it's mainly a matter of reviewing the API's to check for stray uses of ActorSystem over ClassicActorSystemProvider and other things that seem dangerous to commit ourselves to.

2) Check that all runtime API's that are used from the generated code are correctly marked either public API or `@InternalStableApi`

3) Another thing we could do is rebase #768 on top of master and check that these API's work nicely for Akka 2.6 without becoming binary incompatible with master.

4) I haven't thought this through, but I wonder if we could create a scripted test that verifies some API stability?

**Comment by raboof** [comment]
I think this is now done (perhaps excluding some issues already marked for 1.0.0)
