### ISSUE TITLE
Require Akka 2.6

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#762]
Currently, Akka gRPC supports both Akka 2.5 and Akka 2.6.

At some point we will drop support for Akka 2.5 going forward. When would be a good time to do this? We are planning a '1.0' release next year, would it be too early to start requiring Akka 2.6 for that?

Akka 2.5 users could of course still use the 0.x versions, and if there is contributor/customer interest we could backport critial fixes to that branch as well.

My gut feeling is that dropping Akka 2.5 support for 1.0 is too early. Perhaps a good moment to make the switch is when Alpakka is also starting to drop Akka 2.5 support for (all or, more likely, some) connectors. If we indeed decide to keep supporting Akka 2.5 on Akka gRPC 1.0, we should review all API's for which we promise binary compatibility and make sure those still make sense when we make the move to only support Akka 2.6.

**Comment by patriknw** [comment]
One problem is that we generate code that is using deprecated Akka 2.6 APIs (materializer stuff), so if we keep support for 2.5 in 1.0 we would anyway need another branch (1.1) to fully support 2.6.

**Comment by raboof** [comment]
I'm not sure if that's necessarily the case: depending on what binary compatibility guarantees we want to keep (#761) perhaps we don't need to keep generated classes binary compatible. For the runtime we might be able to move to using API's that are not deprecated in Akka 2.6 without removing the methods that need to be kept for binary compatibility reasons. We'd have to test this and it indeed might require changes before we cut 1.0, though.

**Comment by patriknw** [comment]
> I'm not sure if that's necessarily the case

but how would you solve generating code that:
* compiles with 2.5
* and doesn't contain deprecation warnings when compiled with 2.6?

**Comment by raboof** [comment]
Indeed that combination is not possible, but it might not be necessary: suppose:

* 1.0.0 compiles with 2.5 and with 2.6 (but contains deprecation warnings on 2.6)
* 1.0.x drops support for 2.5, keeps any signatures for which we need to maintain binary compatibility, but switches to calling the non-deprecated Akka 2.6 methods instead of the deprecated ones

Though perhaps dropping 2.5 support in itself a change large enough to justify bumping the version to 1.1.0

**Comment by patriknw** [comment]
> compiles with 2.5 and with 2.6 (but contains deprecation warnings on 2.6)

That is the situation we have right now. Some people have strong opinions about that it's not acceptable to have deprecation warnings in the generated code (and I can emphasize with that), see https://github.com/akka/akka-grpc/pull/694

> Though perhaps dropping 2.5 support in itself a change large enough to justify bumping the version to 1.1.0

yes, it is, and we would also need two branches to be able to backport and release critical bugs

That said, if we think 2.5 support in a 1.0 is important we can do 1.0 and 1.1, starting out with the only difference in the code generation.

**Comment by raboof** [comment]
> if we think 2.5 support in a 1.0 is important we can do 1.0 and 1.1, starting out with the only difference in the code generation

So releasing both 1.0.0 (with 2.5 support) and 1.1.0 (2.6-only) early 2020, and keeping 1.1.x backwards compatible with 1.1.x, only backporting selected features to 1.0.x? I think I like that idea.

**Comment by patriknw** [comment]
sounds good to me, otherwise we would have to do pretty much the same but backporting to 0.x instead

**Comment by huntc** [comment]
> Currently, Akka gRPC supports both Akka 2.5 and Akka 2.6.

Is that the case? I've just tried running an Akka gRPC program along with Akka 2.6 and see the following:

```
Exception in thread "main" java.lang.IllegalStateException: Detected possible incompatible versions on the classpath. Please note that a given Akka version MUST be the same across all modules of Akka that you are using, e.g. if you use [2.6.4] all other modules that are released together MUST be of the same version. Make sure you're using a compatible set of libraries. Possibly conflicting versions [2.5.31, 2.6.4] in libraries [akka-discovery:2.5.31, akka-actor-typed:2.6.4, akka-actor:2.6.4, akka-slf4j:2.6.4, akka-protobuf-v3:2.6.4, akka-stream:2.6.4]
```

**Comment by raboof** [comment]
We have seen this error message to be confusing to more people, so from 2.6.5 onwards it will look like this: 

> You are using version 2.6.4 of Akka, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version 2.6.4 of the [akka-discovery] artifacts to your project. See also: https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed

Is that clearer?

**Comment by huntc** [comment]
> Is that clearer?

Wonderful! Thanks!

**Comment by raboof** [comment]
Done in #768
