### ISSUE TITLE
Can we have custom explicit error message in GrpcServiceException?

### ISSUE THREAD

**Issue by lima-da** [akka/akka-grpc#808]
### Short description

Please describe the feature you'd like to see in short.

### Details

Explain your idea in more detail and possibly suggest different ways to achieve it. 

I want my client to receive explicit messages: GrpcServiceException(msg: String, status: Status)
maybe worth extending?

**Comment by raboof** [comment]
`io.grpc.Status` already allows setting a custom description with `status.withDescription("my custom description")` - does that work for you?

**Comment by lima-da** [comment]
Thanks @raboof  I missed out that. `.withDescription` works. I will close the issue.

**Comment by raboof** [comment]
:+1: related to #701
