### ISSUE TITLE
Client-side load balancing with Akka Discovery

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#809]
Client-side loadbalancing with 'static' (or 'grpc-dns') discovery mechanisms is already supported.

There are 2 ways we could implement client-side load balancing with other discovery mechanisms:

* Plug in service discovery into the grpc-java client through the [NameResolver](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/NameResolver.java) interface and use that.
* Support HTTP2 and loadbalancing in the akka-http client and switch to that.

**Comment by ennru** [comment]
Relates to https://github.com/akka/akka-http/issues/2828

**Comment by raboof** [comment]
while there can be more to gRPC load balancing (see for example https://grpc.io/blog/grpc-load-balancing/), #811 implements the basic functionality. Let's close this issue and open more specific issues when we want to implement further features.
