### ISSUE TITLE
Akka gRPC 1.0.0 plans

### ISSUE THREAD

**Issue by ennru** [akka/akka-grpc#827]
We expect to fix up a few things in Akka gRPC and go for 1.0.0 in Q2 2020.

We already consider Akka gRPC production-ready for use in projects: the implementation is well-tested and network API's (being defined by the gRPC protocol) are stable. The main relevance of 1.0.0 is that we start providing binary compatibility (#761), making Akka gRPC more suitable for use in libraries.

See [the milestone](https://github.com/akka/akka-grpc/milestone/13) for what is currently scheduled for 1.0.0

**Comment by raboof** [comment]
See #1008 for progress
