### ISSUE TITLE
Bidirectional Streaming Load Balancing

### ISSUE THREAD

**Issue by jdneumeyer77** [akka/akka-grpc#880]
### Background
Currently our services are using ScalaPB only in a request/response with grpc-dns type load balancing. During heavy load this opens too many sockets and is causing file descriptor issues and tipping things over.

I've re-implemented this using Akka gRPC with a bidirectional streams to keep a persistent connection open. This has helped with the load issues; however, according to our dashboards the load is not evenly distributed.

### Actual Behavior
Uneven load amongst the connected backend servers using grpc-dns and round-robin settings for bidirectional streams. For example we have 10 ingestion servers are connecting to 4 backend servers. Backend server 1 may be getting only say 50 op/s while backend servers 2-3 might be getting 100 op/s and server 4 gets 50 op/s when they should be relatively close. in this case roughly 75 op/s each.

It seems like the DNS round robin'ing is working; however, it only round robins when a reconnect is required, i.e. the stream error or completes, connection issues, etc.. So it's only creating one persistent connection for one of the resolved IP addresses. This may be the first resolved ip from the domain which may be in a random order.

### Expected Behavior 
I was expecting it resolve the IPs and make a persistent connection per resolved IP. Then round robin among those IPs evenly from the input source stream passed into the generated method.

### Versions 
Akka: 2.5.30
Akka-GRPC: 0.8.0

### Test Cases
@ignasi35 mentioned issue #811 is related specifically filling in and testing the bidirectional stream, i.e. streamHellos method in `LoadBalancingIntegrationSpec.scala`. I'll see if I can reproduce that behavior locally to confirm what I'm seeing. Otherwise it's a good starting point for whoever else is looking at this issue.

**Comment by ignasi35** [comment]
> @ignasi35 mentioned ...

😅 In https://gitter.im/akka/akka?at=5e73d9dadfd5f12479c939e0 the discussion was a bit more limited and I had a vague view compared to this very detailed description (see above).

The behavior described above (a client opens multiple `Channel`s to target servers and load balances over those) is not supported, but I think #811 does provide support for a bidi streaming connection to reconnect to a separate backend server when disconnected. That is, the underlying `Channel` is seamlessly used by strict and streamed connections so the tests in #811 should apply for bidi streams.

**Comment by jdneumeyer77** [comment]
I was discussing this with a colleague and I had also read an article that stated it pretty concisely:

```gRPC is limited to HTTP/2 load balancing. You cannot load balance unary gRPC calls differently than Streaming calls. This means that a short-lived request/reply call is load-balanced the same as a long-running stream.```

So maybe this is a use case that gRPC isn't meant to handle. If that's the case we can probably just close this ticket if this isn't how gRPC is meant to be used. It certainly begs the question though. What does it mean to load balance a bidirectional stream?

@ignasi35 PR would provide a way to do the initial balancing though, but I'm not sure how I would remove them from rotation if a backend server goes down. So it's something I can look into too. Another option might be I need to set the number of file descriptors higher and make sure keep alive is enabled as my colleague suggested.

**Comment by raboof** [comment]
If you make 1 bidirectional streaming call, this is "one request" in which the elements streaming to and from the server are guaranteed to arrive at the server in the same order they were sent from the client, and (if/when it completes) with one final return status code.

Because of these semantics, AFAICS it would not make sense to 'load balance' the elements from one streaming request over multiple server endpoints: the ordering would be lost, and it would be hard to decide what status code to return (if any) for example when one of the endpoints fails but another one is still going strong.

If you don't care about the ordering of the elements, you could consider sending them as unary calls, or opening a number of streaming calls (at least as many as you expect endpoints ;) ).

Does that make sense?

**Comment by jdneumeyer77** [comment]
In this case order does not matter nor to which endpoint the message was sent to. Unary calls is the current working solution. Due to spikes and their duration in load, and the number of incoming connections (not grpc, but the ingress at the ingestion process which cannot reuse these connections unfortunately) we thought maybe persistent connections between ingestion server and the backend would alleviate that problem. Which why I'm looking at Akka Grpc. I thought bidirectional streams would load balance at the message/element level across multiple streams, i.e. persistent connections, but that is not the case. I would recommend at least stating that in the documentation as it is not clear whether it's at the stream or element level of the stream, or it could be a limitation of gRPC that I missed.

So my options with gRPC are to stick with unary calls (possibly tweaking keep-alive, max file descriptors, etc.) or manually load balance across $x number of clients/streams. The latter of which would be a lot easier if Akka Grpc offered the client as a Flow as opposed to a Source.

**Comment by raboof** [comment]
> Unary calls is the current working solution. Due to spikes and their duration in load, and the number of incoming connections (not grpc, but the ingress at the ingestion process which cannot reuse these connections unfortunately) we thought maybe persistent connections between ingestion server and the backend would alleviate that problem

If you make many unary calls, they should already be multiplexed over the same HTTP/2 TCP connection, though, right? I don't think switching between unary and streaming would affect the number of connections.

> would be a lot easier if Akka Grpc offered the client as a Flow as opposed to a Source

I agree this would be helpful to provide, but it is indeed not currently part of the API.

**Comment by jdneumeyer77** [comment]
That is what I thought. Maybe this it's a configuration issue or a dependency issue. Somewhat off-topic as far as Akka Grpc goes, but I'm having trouble finding this information. In the case of Java 8, TLS disabled, i.e. plaintext, ScalaPB and Netty does one need Jetty ALPN or does Netty provide that? It seems like netty-tcnative provides it for TLS connections. If that's the case maybe the connection isn't getting promoted from HTTP 1.1 to 2.0? So it won't be multiplexed?

Also thanks for the help. I think I'll close this issue as it's as designed. As gRPC's load balancing strategies evolve an element based load balancer seems possible and even easy with Akka gRPC, but that seems like more of a feature request than a bug request.
