### ISSUE TITLE
maven-plugin uses old protoc-jar version

### ISSUE THREAD

**Issue by dotbg** [akka/akka-grpc#884]
the protoc-jar version, used during generation is hardcoded as "351". The project depends on the protoc-jar v3.11.4

**Comment by dotbg** [comment]
@raboof Is it possible to do a release ? I want to make use of the plugin, but it won't work without this change

**Comment by raboof** [comment]
I'm surprised the plugin won't work without this change - it worked fine for our Travis jobs that do test maven projects (both Java and Scala). Do you know why we didn't notice it there?

That said, we regularly publish snapshot releases to https://bintray.com/akka/maven/akka-grpc . Versions `0.8.1+2-499a5833` and later should have this change.

When using maven, you have to add this repository to your `settings.xml` like this:

```
<?xml version='1.0' encoding='UTF-8'?>
<settings xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd' xmlns='http://maven.apache.org/SETTINGS/1.0.0' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
<profiles>
   <profile>
       <repositories>
           <repository>
               <snapshots>
                   <enabled>false</enabled>
               </snapshots>
               <id>bintray-akka-maven</id>
               <name>bintray</name>
               <url>https://dl.bintray.com/akka/maven</url>
           </repository>
       </repositories>
       <pluginRepositories>
           <pluginRepository>
               <snapshots>
                   <enabled>false</enabled>
               </snapshots>
               <id>bintray-akka-maven</id>
               <name>bintray-plugins</name>
               <url>https://dl.bintray.com/akka/maven</url>
           </pluginRepository>
       </pluginRepositories>
       <id>bintray</id>
   </profile>
</profiles>
<activeProfiles>
   <activeProfile>bintray</activeProfile>
</activeProfiles>
</settings>
```

**Comment by dotbg** [comment]
@raboof the problem is in this line https://github.com/os72/protoc-jar/blob/master/src/main/java/com/github/os72/protocjar/Protoc.java#L415

I use Mac and am getting the following issue during code generation
` 
java.io.FileNotFoundException: Unsupported platform: protoc-3.5.1-osx-x86_64.exe
    at com.github.os72.protocjar.Protoc.extractProtoc (Protoc.java:223)
    at com.github.os72.protocjar.Protoc.extractProtoc (Protoc.java:184)
    at com.github.os72.protocjar.Protoc.runProtoc (Protoc.java:68)
    at com.github.os72.protocjar.Protoc.runProtoc (Protoc.java:55)
`

**Comment by raboof** [comment]
OK - and it does work with Akka gRPC `0.8.1+2-499a5833`?

**Comment by dotbg** [comment]
yes, it does work that way. Thank you.
I'll only have to make this resolvable within our company's artifactory.
