### ISSUE TITLE
Regression in 0.8.0 - client sends wrong host header

### ISSUE THREAD

**Issue by fredfp** [akka/akka-grpc#898]
Since switching to 0.8.[012], using akka-grpc as client doesn't work when going through a reverse proxy relying on host header to forward connection to the right grpc server.

The load balancer decodes the requested host as `static` instead of the host given in `GrpcClientSettings.connectToServiceAt("host.lb.com", 80)`.

I think the regression comes from this line in a recent commit https://github.com/akka/akka-grpc/commit/96e15516f6ce78b3ac0530491c1da104952e5710#diff-977da58f66c832d603f6ad9ac553d99dR48 where `settings.serviceName` seems to be the name of the service discovery method (`static`) instead of the targeted hostname.

**Comment by raboof** [comment]
Yes, I just ran into the same issue. As a workaround I *think* you should be able to set the `override-authority` client setting, but we should definitely fix the default here.

**Comment by raboof** [comment]
I _think_ this should be fixed by setting https://github.com/akka/akka-grpc/blob/master/runtime/src/main/scala/akka/grpc/GrpcClientSettings.scala#L111 to the host+port, but that needs validating/testing. I'll look into it tomorrow, unless of course someone beats me to it :smile:

**Comment by fredfp** [comment]
I gave it a try setting service-name to host only, not sure about the host+port part you mentioned as it's not part of service-name with other discovery methods.

**Comment by raboof** [comment]
Should be fixed with 0.8.4, feel free to reopen (or open a separate issue) when the lack of a port number causes problems.

**Comment by pavlo-t** [comment]
Lack of port number causes problems with linkerd proxy in front of a service on a custom port after switching to 1.0.1.
For now this seems to work:
```scala
def staticClientSettings(clientName: String): GrpcClientSettings = {
  val config = system.settings.config.getConfig(s"akka.grpc.client.\"$clientName\"")
  val host = config.getString("host")
  val port = config.getInt("port")
  GrpcClientSettings
    .usingServiceDiscovery(
      s"$host:$port",
      new HardcodedServiceDiscovery(Resolved(host, immutable.Seq(ResolvedTarget(host, Some(port), None))))
    )
    .withDefaultPort(port)
}
```
But it would be nice to use `GrpcClientSettings.fromConfig("my-service")` again

**Comment by fredfp** [comment]
@pavlo-t I would create a new issue and reference this one. A PR is always appreciated!
