### ISSUE TITLE
Akka 2.6.0, generated-sources compile error

### ISSUE THREAD

**Issue by Aincvy** [akka/akka-grpc#908]
### Versions used 0.8.4

Akka version: 2.6.0

### Behavior
Generated-sources compile error.
Maven plugin:
  - com.lightbend.akka.grpc
  - akka-grpc-maven-plugin
  - 0.8.4

Code:
  - Example code
  - link: [click](https://doc.akka.io/docs/akka-grpc/current/proto.html)
  - File/Class:  `GreeterServiceHandlerFactory.java`
  - Method `create(GreeterService implementation, String prefix, ClassicActorSystemProvider system) `   .Error statement: `SystemMaterializer.get(system).materializer()`
  - Fix Method: change to `SystemMaterializer.get(system.classicSystem()).materializer()`

### Relevant logs
Nothing.

### Reproducible Test Case
Nothing.

**Comment by Aincvy** [comment]
After fix compile error, I try to run the example program, it works fine.

**Comment by raboof** [comment]
Thanks for your report.

You are correct that, when using Akka 2.6, this generated code requires at least Akka 2.6.1. Would it be possible to upgrade (perhaps directly to 2.6.4?)

It would be good to add a testcase for this Java DSL as a scripted test, like done in #906 for Scala

**Comment by Aincvy** [comment]
After upgrade to 2.6.4, it works fine. 

Thank you for your help.

**Comment by raboof** [comment]
Good to hear!
