### ISSUE TITLE
'Accessing request metadata' doc  need a supplement

### ISSUE THREAD

**Issue by Aincvy** [akka/akka-grpc#911]
### Short description
**In server-side**
It should mention the `HandlerFactory`. 
e.g
When do not using metadata, use `GreeterServiceHandlerFactory.create()`.
When using metadata, use `GreeterServicePowerApiHandlerFactory.create()`.

Official document, link: [click](https://doc.akka.io/docs/akka-grpc/current/server/walkthrough.html#accessing-request-metadata) .

<hr />  

**In client-side**

I think it should mention the method `addHeader` 's features.
  - `addHeader` returns a new entity.
  - `addHeader` not change it self.
  - `addHeader` usage like `string.xxx`, not like `ProtoBuf MessageBuilder`

### Details

In my way, if the client-side use metadata, then the server-side will drop request.
If I use `GreeterServicePowerApiHandlerFactory`, it works fine.

**Comment by raboof** [comment]
Great points! I agree we should document those.

I wonder if, for the server side, we should change the API so `GreeterServiceHandlerFactory.create()` can be used both for power and 'normal' implementations.

Would you be interested in PR'ing?

**Comment by Aincvy** [comment]
I can't write scala, no any experience, sorry.

I only can write Java, C#, a little js.

**Comment by raboof** [comment]
Only an update to the docs would be helpful already (they're in markdown in the 'docs/src/main/paradox' folder) ;) - in any case thanks for the heads-up!

**Comment by Aincvy** [comment]
OK,  I will try when I am idle.

**Comment by ignasi35** [comment]
Hi @Aincvy, did you intend to close this issue? 

We usually keep the issue open until the corresponding PRs have been merged.

**Comment by Aincvy** [comment]
> Hi @Aincvy, did you intend to close this issue?
> 
> We usually keep the issue open until the corresponding PRs have been merged.

OK,  got it.

**Comment by raboof** [comment]
(this was done in #941)
