### ISSUE TITLE
Expose option to generate the standard types

### ISSUE THREAD

**Issue by claudio-scandura** [akka/akka-grpc#917]
### Short description

I have come across this issue while generating sources for proto files that include references to standard schemas. The source generation step fails because the standard Protobuf types are not included in the compilation.
I have only experienced this with the Maven plugin and have not tried SBT, so I don't exclude that this issue applies there too.

### Details
If you try to generate sources for the following proto snippet using the Maven plugin it will wail because it won't find the ` google.protobuf.Timestamp` type.
```
syntax = "proto3";

import "google/protobuf/timestamp.proto";

message Test {
    google.protobuf.Timestamp updatedAt = 1;
}
```
This can be worked around with a bit of a hack where when setting up the plugin we use the `protocVersion` config to inject the `--include_std_types` param.

```
<plugin>
      <groupId>com.lightbend.akka.grpc</groupId>
      <artifactId>akka-grpc-maven-plugin</artifactId>
      <configuration>
          <protocVersion>--include_std_types</protocVersion>
      </configuration>
</plugin>
```
Luckily this is passed all the way down by the plugin and it works.

### Possible solutions
Ideally, any extra argument should be injectable by the user to allow customisation, so another field of type List could be added to the xml schema.
Alternatively, the specific argument `--include_std_type` could be modelled as a boolean flag in the xml schema and possibly defaulted to true as I would imagine it to be quite common to use standard types in proto definitions.

**Comment by raboof** [comment]
> ###
> 
> Ideally, any extra argument should be injectable by the user to allow customisation, so another field of type List could be added to the xml schema.
> Alternatively, the specific argument `--include_std_type` could be modelled as a boolean flag in the xml schema and possibly defaulted to true as I would imagine it to be quite common to use standard types in proto definitions.

(I took the liberty of renaming this issue to describe this alternative, since that is the direction @dotbg is taking in #1136)

**Comment by dotbg** [comment]
I believe, this issue can be closed now, @raboof ?

**Comment by raboof** [comment]
Yes, thanks again for a great contribution!
