### ISSUE TITLE
Publish the akka-grpc-codegen package for Scala 2.13

### ISSUE THREAD

**Issue by tjarvstrand** [akka/akka-grpc#949]
### Short description

Publish the akka-grpc-codegen package for Scala 2.13

### Details

Would it be possible to publish the akka-grpc-codegen package for Scala 2.13? I see that 2.13 has been [explicitly excluded in the build-file](https://github.com/akka/akka-grpc/blob/52f006d6269ff7867d1abe39e92acb2d6c8486bb/build.sbt#L36).

I've been working on a [mill plugin for akka-grpc](https://github.com/tjarvstrand/mill-akka-grpc). Mill just made the switch to Scala 2.13 however so my plugin will not work in versions >= 0.7.0 since akka-grpc-codegen will not be available.

**Comment by raboof** [comment]
> I've been working on a mill plugin for akka-grpc

That is very cool!

> Mill just made the switch to Scala 2.13

That's a great reason to release the codegen for 2.13 as well - I'll have a look.

**Comment by tjarvstrand** [comment]
Thanks! :)

**Comment by raboof** [comment]
No problem! It'll be part of the next release, until that time you can test with snapshot version 0.8.4+28-007b0e05 from https://bintray.com/akka/maven/akka-grpc

**Comment by raboof** [comment]
Unfortunately it looks like I broke this when switching to releasing directly to sonatype, specifically in 18bcff9359f2ff4ac58a944c4a0f5e09270e82c5 - sorry about that. Filed #1400 to bring this back.
