### ISSUE TITLE
gRPC client broken for Java

### ISSUE THREAD

**Issue by politrons** [akka/akka-grpc#961]
I'm following the documentation, and the example is not working

https://doc.akka.io/docs/akka-grpc/current/client/walkthrough.html#setting-up

Everything compile just fine, but when I run the client, it seems like it try to get a config file to create `GrpcClientSettings` which I dont know which one it require since the documentation it does not mention.

`        GrpcClientSettings settings = GrpcClientSettings.fromConfig(GreeterService.name, system);
`

Then I receive the error 

```
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Config path `akka.grpc.client.com.ing.connector.grpc.GreeterService` does not exist
	at scala.Predef$.require(Predef.scala:281)
	at akka.grpc.GrpcClientSettings$.fromConfig(GrpcClientSettings.scala:60)
	at akka.grpc.GrpcClientSettings.fromConfig(GrpcClientSettings.scala)
	at com.ing.connector.grpc.GreeterClient.main(GreeterClient.java:30)
```

Any fix for this?

**UPDATE** 

I just found you need to add a reference.conf in the resource if you want to go by this option. You should add it in the documentation.

Now that I manage to fix this, I found this other problem

`        GrpcClientSettings settings = GrpcClientSettings.connectToServiceAt(serverHost, serverPort, system);`

Regards.

**Comment by raboof** [comment]
> You should add it in the documentation.

I agree we should start by showing configuration by code in the walkthrough, and then go into configuring by application.conf on the 'configuration' page. Added #965.

> Now that I manage to fix this, I found this other problem

What is the problem? :)

**Comment by ennru** [comment]
As #965 improved the documentation and we don't understand what "this other problem" is, I'll close this. 
Please open a new issue if there is something that can be improved.
