### ISSUE TITLE
Generate deterministic server code

### ISSUE THREAD

**Issue by charlietsai** [akka/akka-grpc#988]
### Short description

Currently, the server codegen is not deterministic, as the generated `Serializers` may change ordering. In cases where we want to examine the generated code, this leads to unnecessary diffs.

### Details

It looks like [`serializers` is created as a set](https://github.com/akka/akka-grpc/blob/9fd7d62ad197dc19aed9e0ed30cdc09a97cee380/codegen/src/main/scala/akka/grpc/gen/scaladsl/Service.scala#L22):
```scala
  def serializers: Set[Serializer] = (methods.map(_.deserializer) ++ methods.map(_.serializer)).toSet
```
which is then [iterated through in the template](https://github.com/akka/akka-grpc/blob/6dc615dcca93460e56cc5795a09c28b2d9f7c62f/codegen/src/main/twirl/templates/ScalaCommon/ApiTrait.scala.txt#L28):
```scala
    @for(serializer <- service.serializers) {
```

Since the default set does not guarantee ordering, the order of the serializers may change in subsequent runs of the codegen.

Not an issue if we don't care to guarantee the codegen is deterministic, but I'm wondering if a simple change like this would still work?
```diff
--- a/codegen/src/main/scala/akka/grpc/gen/scaladsl/Service.scala
+++ b/codegen/src/main/scala/akka/grpc/gen/scaladsl/Service.scala
@@ -19,7 +19,7 @@ case class Service(
     serverPowerApi: Boolean,
     usePlayActions: Boolean,
     comment: Option[String] = None) {
-  def serializers: Set[Serializer] = (methods.map(_.deserializer) ++ methods.map(_.serializer)).toSet
+  def serializers: Seq[Serializer] = (methods.map(_.deserializer) ++ methods.map(_.serializer)).distinct
   def packageDir = packageName.replace('.', '/')
 }
```

**Comment by raboof** [comment]
> Not an issue if we don't care to guarantee the codegen is deterministic

I think it's worth it to make the codegen deterministic

> I'm wondering if a simple change like this would still work?

Possibly! Would you like to provide a PR?

**Comment by charlietsai** [comment]
Sure, I'll give it a try!
